<!DOCTYPE html>
<html>

<head>

<title>Help Me Grow Utah</title>
<link rel="stylesheet" href="css/home.css" />

</head>

<body>
	<div class="wrapper bottom-border">
		<div class="header">
			<img class="header_logo" src="images/HMGU-logo-white.png" />
			<p class="byline">Bringing childhood to life</p>
		</div>
	</div>
  

  	<div class="wrapper-main">
  		<div class="main">
  			<img class="main-photo" src="images/child-photo.jpg" />
      		<?=$viewHtml?>
  		</div>
    </div>


	<div class="wrapper top-border">
		<div class="footer">
		<div class="united-way-logo">
			<img src="images/united-way-logo.png" />
		</div>
		<p>Help Me Grow Utah is a proud member of the Help Me Grow National Network<p>
		<p>www.helpmegrowutah.org</p>
		</div>
	</div>
		
    
 </body>
</html>

