<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN"
  "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" version="XHTML+RDFa 1.0" dir="ltr"
  xmlns:content="http://purl.org/rss/1.0/modules/content/"
  xmlns:dc="http://purl.org/dc/terms/"
  xmlns:foaf="http://xmlns.com/foaf/0.1/"
  xmlns:og="http://ogp.me/ns#"
  xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
  xmlns:sioc="http://rdfs.org/sioc/ns#"
  xmlns:sioct="http://rdfs.org/sioc/types#"
  xmlns:skos="http://www.w3.org/2004/02/skos/core#"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema#">

<head profile="http://www.w3.org/1999/xhtml/vocab">
  <title>Help Me Grow Utah</title>

<style type="text/css" media="all">@import url("http://helpmegrowutah.org/sites/helpmegrowuc.org/files/fontyourface/local_fonts/joyful_julianna-normal-normal/stylesheet.css?mktfjx");</style>
<link rel="stylesheet" href="css/style_subs.css" />
<link rel="stylesheet" href="css/hmg.css" />
<link rel="stylesheet" type="text/css" href="css/colors.css" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

<script src="http://code.jquery.com/jquery-latest.js"></script>
</head>
<body class="html front not-logged-in one-sidebar sidebar-first page-node page-node- page-node-20 node-type-page" style="background: #fff;" >
  
	<div id="mainWrapperDb"> <!-- BEGIN MAINWRAPPER -->
      <div id="wrapper" class="clearfix"> <!-- BEGIN WRAPPER -->
        
			<div id="main-content" style="background: #fff; margin-top: 0; padding: 5px 5px;"> <!-- BEGIN CONTENT -->
			

    		<?=$viewHtml?>

			
			</div> <!-- END CONTENT -->
		</div> <!-- END WRAPPER -->
    </div> <!-- END MAINWRAPPER -->
    
		
  </body>
</html>
