		<div class="titleBar" style="padding: 0 10px;"><span class="caption" style="">Child Developmental Screening</span></div>
	<form id="developmental-screening-form" class="development-screening-form" action="index.php" method="get" onsubmit="return false;" enctype="multipart/form-data">
		<input type="hidden" name="action" value="child-developmental-screening" />
		<input type="hidden" id="child-id" name="developmentScreening[child_id]" value="<?= $child_id ?>" />
		<input type="hidden" id="id" name="developmentScreening[id]" value="<?= (isset($developmentalScreening) ? $developmentalScreening['id'] : '') ?>" />
		<div style="padding: 10px">
		<table id="screening-form-table">
			<tbody>
				<tr>
					<td class="label">Screening Type</td>
					<td>
						<?= $screening_type->displaySelect('developmentScreening[type]', (isset($developmentalScreening['type']) && $developmentalScreening['type'] ? $developmentalScreening['type'] : ''), ' ', '100', false, ' screening-type', false, false) //261016 revert back ?>
					</td>
					<td class="label">Date Completed</td>
					<td>
						<input name="developmentScreening[date_sent]" value="<?= (isset($developmentalScreening['date_sent']) && $developmentalScreening['date_sent'] != '0000-00-00' ? $developmentalScreening['date_sent'] : '') ?>" class="date" tabindex="140" />
					</td>
				</tr>
				<tr>
					<td class="label">Screening Interval</td>
					<td>
						<?= $screening_interval->displaySelect('developmentScreening[asq_month]', (isset($developmentalScreening['asq_month']) && $developmentalScreening['asq_month'] ? $developmentalScreening['asq_month'] : ''), ' ', '120', false, ' screening-interval', false, true) ?>
					</td>

					<td class="label">Date Faxed</td>
					<td>
						<input name="developmentScreening[date_sent_provider]" value="<?= (isset($developmentalScreening['date_sent_provider']) && $developmentalScreening['date_sent_provider'] != '0000-00-00' ? $developmentalScreening['date_sent_provider'] : '') ?>" class="date" tabindex="170" />
					</td>
				</tr>
				<tr>
					<td class="label">Score</td>
					<td>
						<?= $score->displaySelect('developmentScreening[score]', (isset($developmentalScreening['score']) && $developmentalScreening['score'] ? $developmentalScreening['score'] : ''), ' ', '130', false, ' screening-score', false, false) ?>
					</td>
					<td class="label">ASQ SE Score</td>
					<td>
						<input name="developmentScreening[asq_se_score]" value="<?= (isset($developmentalScreening['asq_se_score']) ? $developmentalScreening['asq_se_score'] : '') ?>" tabindex="230">
					</td>
				</tr>
				<tr>
					<td class="label" rowspan="2" valign="top">ASQ 3</td>
					<td rowspan="2" valign="top">
						<input name="developmentScreening[communication]" type="hidden" value="0" />
						<input name="developmentScreening[fine_motor]" type="hidden" value="0" />
						<input name="developmentScreening[gross_motor]" type="hidden" value="0" />
						<input name="developmentScreening[problem_solving]" type="hidden" value="0" />
						<input name="developmentScreening[personal_social]" type="hidden" value="0" />
						<table id="asq3-table">
							<tr>
								<td>&nbsp;</td>
								<td>White</td>
								<td>Grey</td>
								<td>Black</td>
							</tr>
							<tr>
								<td>Communication</td>
								<td align="center"><input name="developmentScreening[communication]" type="radio" value="Black"<?= (isset($developmentalScreening['communication']) && $developmentalScreening['communication'] == 'Black' ? ' checked' : '') ?> tabindex="180"></td>
								<td align="center"><input name="developmentScreening[communication]" type="radio" value="Grey"<?= (isset($developmentalScreening['communication']) && $developmentalScreening['communication'] == 'Grey' ? ' checked' : '') ?> ></td>
								<td align="center"><input name="developmentScreening[communication]" type="radio" value="White"<?= (isset($developmentalScreening['communication']) && $developmentalScreening['communication'] == 'White' ? ' checked' : '') ?>></td>
							</tr>
							<tr>
								<td>Gross Motor</td>
								<td align="center"><input name="developmentScreening[gross_motor]" type="radio" value="Black"<?= (isset($developmentalScreening['gross_motor']) && $developmentalScreening['gross_motor'] == 'Black' ? ' checked' : '') ?> tabindex="200"></td>
								<td align="center"><input name="developmentScreening[gross_motor]" type="radio" value="Grey"<?= (isset($developmentalScreening['gross_motor']) && $developmentalScreening['gross_motor'] == 'Grey' ? ' checked' : '') ?>></td>
								<td align="center"><input name="developmentScreening[gross_motor]" type="radio" value="White"<?= (isset($developmentalScreening['gross_motor']) && $developmentalScreening['gross_motor'] == 'White' ? ' checked' : '') ?>></td>
							</tr>
							<tr>
								<td>Fine Motor</td>
								<td align="center"><input name="developmentScreening[fine_motor]" type="radio" value="Black"<?= (isset($developmentalScreening['fine_motor']) && $developmentalScreening['fine_motor'] == 'Black' ? ' checked' : '') ?> tabindex="190"></td>
								<td align="center"><input name="developmentScreening[fine_motor]" type="radio" value="Grey"<?= (isset($developmentalScreening['fine_motor']) && $developmentalScreening['fine_motor'] == 'Grey' ? ' checked' : '') ?>></td>
								<td align="center"><input name="developmentScreening[fine_motor]" type="radio" value="White"<?= (isset($developmentalScreening['fine_motor']) && $developmentalScreening['fine_motor'] == 'White' ? ' checked' : '') ?>></td>
							</tr>
							<tr>
								<td>Problem Solving</td>
								<td align="center"><input name="developmentScreening[problem_solving]" type="radio" value="Black"<?= (isset($developmentalScreening['problem_solving']) && $developmentalScreening['problem_solving'] == 'Black' ? ' checked' : '') ?> tabindex="210"></td>
								<td align="center"><input name="developmentScreening[problem_solving]" type="radio" value="Grey"<?= (isset($developmentalScreening['problem_solving']) && $developmentalScreening['problem_solving'] == 'Grey' ? ' checked' : '') ?>></td>
								<td align="center"><input name="developmentScreening[problem_solving]" type="radio" value="White"<?= (isset($developmentalScreening['problem_solving']) && $developmentalScreening['problem_solving'] == 'White' ? ' checked' : '') ?>></td>
							</tr>
							<tr>
								<td>Personal Social</td>
								<td align="center"><input name="developmentScreening[personal_social]" type="radio" value="Black"<?= (isset($developmentalScreening['personal_social']) && $developmentalScreening['personal_social'] == 'Black' ? ' checked' : '') ?> tabindex="220"></td>
								<td align="center"><input name="developmentScreening[personal_social]" type="radio" value="Grey"<?= (isset($developmentalScreening['personal_social']) && $developmentalScreening['personal_social'] == 'Grey' ? ' checked' : '') ?>></td>
								<td align="center"><input name="developmentScreening[personal_social]" type="radio" value="White"<?= (isset($developmentalScreening['personal_social']) && $developmentalScreening['personal_social'] == 'White' ? ' checked' : '') ?>></td>
							</tr>
						</table>
						<a href="#" class="clear-developmental-screenings">Clear Selections</a>
					</td>
					<td colspan="2" style="padding-left: 15px;">
						<span class="infoLabel">Attachments:</span>
						<div id="attachment-container">
							<?=$attachment_content?>
							
						</div>
						<iframe id="screening-attachment-frame" scrolling="no" src="views/file-screening.phtml?id=<?=(isset($developmentalScreening['id'])?$developmentalScreening['id']:'')?>&type=screening<?= (isset($developmentalScreening) ? '&show-button=1' : '') ?>" style="width: 200px; height: 20px; margin: 0px; overflow: hidden;"></iframe>
					</td>
				</tr>
				<tr>
					<td valign="top" colspan="2" style="padding-left: 15px;">
						<textarea name="developmentScreening[notes]" cols="40" rows="6" tabindex="250" style="width: 190px; padding: 4px;" placeholder="Screening Notes"><?= (isset($developmentalScreening['notes']) ? $developmentalScreening['notes'] : '') ?></textarea>
					</td>
				</tr>

				<tr>
					<td colspan="4" style="text-align: right;">
						<input type="submit" class="btn-small save-developmental-screening" name="save" value="<?= (isset($developmentalScreening['id']) && is_numeric($developmentalScreening['id']) ? 'Save': 'Add') ?>" tabindex="260" />
						<? if(isset($developmentalScreening['id']) && is_numeric($developmentalScreening['id'])){ ?>
						<input type="submit" class="btn-small delete-developmental-screening" name="delete" value="Delete" tabindex="280" />
						<? } ?>
					</td>
				</tr>
			</tbody>
		</table>
		</div>
	</form>