<? 
$csv = "Counts: Provider\n\n";

$encapsulateField = false;
$filteredByLabel = '';
$filteredBy = '';
if(count($filters)){
	$filteredByLabel = 'Active Filters: ';
}
foreach($filters as $filter => $value){
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter != 'zip' && $filter != 'school_district'){
		$value = $setting->getValue($value);
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter == 'school_district'){
		$value = $schoolDistrict->getSchoolDistrictById($value);
	}
	if($value){
		if(is_array($value)){
			$value = implode($value, ', ');
			$encapsulateField = true;
		}
		$filteredBy .=
			($filteredBy ? ' - ' : '') .
			ucwords(str_replace('_', ' ', str_replace('_id', ' ', $filter))) . 
			': ' . 
			$value;
	}
}
if($encapsulateField){
	$csv .= '"' . $filteredByLabel . $filteredBy . '",,';
} else {
	$csv .= $filteredByLabel . $filteredBy . ',,';
}

if($filteredByLabel){
	$csv .= "\n\n";
} else {
	$csv .= "\n";
}

$csv .= 'Families with Assigned Provider,Count,Pct%' . "\n";
foreach($providerFaxCounts as $row){
	$csv .= str_replace('<br />', ' ', $row['name']) . ',';
	$csv .= $row['cnt'] . ',';
	$csv .= $row['percent'] . "\n";
}

$csv .= "\n" . 'Provider Role,Pct%' . "\n";
foreach($providerRoleCounts as $row){
	$csv .= $row['name'] . ',';
	$csv .= $row['cnt'] . ',';
	$csv .= $row['percent'] . "\n";
}

$csv .= "\n" . 'Professional Referrals,,' . "\n";
$csv .= 'How Did Family Hear?,Count,Pct%' . "\n";
foreach($providerHowHeardCounts as $row){
	$csv .= $row['name'] . ',';
	$csv .= $row['cnt'] . ',';
	$csv .= $row['percent'] . "\n";
}

$csv .= "\n" . 'Providers with the Most Clients,,' . "\n";
$csv .= 'Provider,Clinic/Organization Name,# of clients' . "\n";
foreach($providerMostReferralCounts as $row){
	$csv .= $row['name'] . ',';
	$csv .= $row['employer'] . ',';
	$csv .= $row['cnt'] . "\n";
}

echo $csv;
?>

					                         
