<?php 
//echo "<pre>";print_r($_SERVER);die;
function buildUrl($new) {
	$scheme = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' ? 'https' : 'http';
	$url = $scheme.'://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
	if(empty($scheme) && isset($_SERVER['REQUEST_SCHEME'])) {
		$url = $_SERVER['REQUEST_SCHEME'].'://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
	}

	$url_parts = parse_url($url);
	parse_str($url_parts['query'], $params);

	$params[$new] = true;     // Overwrite if exists
	// Note that this will url_encode all values
	$url_parts['query'] = http_build_query($params);

	// If not
	return $url_parts['scheme'] . '://' . $url_parts['host'] . $url_parts['path'] . '?' . $url_parts['query'];
}
$urlPrint  = buildUrl('print');
$urlExport = buildUrl('export');

?>

<script>
$(function(){

	$('.fancybox').fancybox({
		padding : '0px', scrolling : 'no'
	});

	$(document).on('click', '#print-list', function(e){
		e.preventDefault();
		postString = $('#filter-form').serialize();
		window.open('<?php echo $urlPrint?>');
		//window.open('index.php?print=true&' + postString, '');
	});
	$(document).on('click', '#export-list', function(e){
		e.preventDefault();
		postString = $('#filter-form').serialize();
		
		window.open('<?php echo $urlExport?>');

	});
	$(".sort").on("click", function(){
		field = ($(this).text().replace(/ /g, '_').toLowerCase());
		if($(this).hasClass('sorting_asc')){
			$(this).removeClass('sorting_asc').addClass('sorting_desc');
			fieldsort = 'desc';
		}
		else if($(this).hasClass('sorting_desc')){
			$(this).removeClass('sorting_desc').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		else {
			$(this).removeClass('sorting').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		if(field == 'reason_for_call'){
			field = 'call_reason';
		}
        if(field == 'organization'){
			field = 'organization_name';
		}
        if(field == 'hmg_worker'){
			field = 'hmgworker';
		}
        
        
		location.href="index.php?action=counts&type=eventsDrill&substatus=<?=$substatus ?>&field="+field+"&sort="+fieldsort<?= ($search ? '+"&search=' . $search . '"' : '')?><?= (isset($this->drillName) ? '+"&drillName=' . $this->drillName . '"' : '')?><?= (isset($this->subvalue) ? '+"&subvalue=' . $this->subvalue . '"' : '')?>;
	});

	function comparer(index) {
	    return function(a, b) {
	        var valA = getCellValue(a, index), valB = getCellValue(b, index)
	        return $.isNumeric(valA) && $.isNumeric(valB) ? valA - valB : valA.localeCompare(valB)
	    }
	}
	function getCellValue(row, index){ return $(row).children('td').eq(index).html() }

	$('#multi-zip').on('change', function(e){
		var checkbox = this;
		$('.select').attr('multiple',checkbox.checked);
	 	if(checkbox.checked){
	 		$('.select').attr('name','filters[zip][]');
	 		$('.select').attr('size','11');
	 	} else {
	 		$('.select').attr('name','filters[zip]');
	 		$('.select').attr('size','1');
	 	}
	});

	$('.date').datepicker();
});
</script>
<div class="pageTitleBar">
	<a href="index.php?action=counts"><h1>Outreach Events Demographics</h1></a>

	<div style="float: right; padding: 0px 4px 4px 0; margin-left: 10px;">
		<form id="filter-form" action="index.php" style="padding: 8px 3px 0 4px;">
			<input type="hidden" name="action" value="counts">
			<input type="hidden" id="count-family" name="type" value="eventsDrill">
			<input type="hidden" name="drillheading" value="<?php echo isset($_REQUEST['drillheading']) ? $_REQUEST['drillheading'] : ''?>">
            <input type="hidden" name="substatus" value="<?php if(isset($this->substatus) && !empty($this->substatus)) echo $this->substatus; ?>">
		      <input type="hidden" name="subvalue" value="<?php if(isset($this->subvalue) && !empty($this->subvalue)) echo $this->subvalue; ?>">
		
			<div style="float: right; margin-left: 60px">
			<input type="submit" class="btn-small" id="export-list" name="export_list" value="Export" />
			<input type="submit" class="btn-small" id="print-list" name="export_list" value="Print" />
			<input type="submit" class="btn-small" value="Counts" onclick="$('#count-family').val(0);" />
			
			</div>
			<style>
			select.status{
				width: auto;
			}
			.pageTitleBar input[type="text"] {
				width: 80px;
			}
			.school_district, .select, .filter {
				display: inline-block;
				float: left;
				margin-right: 2px;
				margin-top: 2px;
			}
			.counts-county{
				float: left;
				margin-right: 2px;
				margin-top: 2px;
			}
			.select-wrapper {
				float: left;
				margin-right: 20px;
			}
			.filter-container {
				float: left;
				margin: auto 0;
			}
			#multi-zip{
				vertical-align: middle;
			}
			a.familyLinks { color: #464646; text-decoration: none; }
			a.familyLinks:hover { text-decoration: underline; }
			a.childLinks { color: #464646; text-decoration: none; }
			a.childLinks:hover { text-decoration: underline; }
			</style>
			<div class="filter-container">
				<?= $region->displaySelect('filters[region_id]', $filters['region_id'], 'Region', false, null, 'filter') ?>
				
				<?= $status->displaySelect('filters[status]', $filters['status'], 'Status', '', false, ' counts-status', false) ?>
				<input type="text" class="date" id="start-date" name="filters[start_date]" value="<?= $filters['start_date'] ?>" placeholder="Start Date" />
				<input type="text" class="date" id="end-date" name="filters[end_date]" value="<?= $filters['end_date'] ?>" placeholder = "End Date" />
				<input type="submit" value="Filter" class="btn-small" />  <input type="submit" name="clearFilters" value="Clear" class="btn-small" />

			</div>
			<a href="#counts-advanced-search" class="fancybox" style="font-size: 10px !important; line-height: 10px; font-weight: bold; display: inline-block; margin-left: 10px; text-align: center;">Advanced<br /> Search</a>
		</form>
	</div>
</div>

<div style="width: 100%; margin-bottom: 5px; clear: both;">
<?
$filteredByLabel = '';
$filteredBy = '';
if(count($filters)){
	$filteredByLabel = '<b style="color: #464646">Active Filters: </b>';
}
foreach($filters as $filter => $value){
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter != 'zip' && $filter != 'school_district'){
		$value = $setting->getValue($value);
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter == 'school_district'){
		$value = $schoolDistrict->getSchoolDistrictById($value);
	}
	if($value){
		if(is_array($value)){
			$value = implode($value, ', ');
		}
		$filteredBy .=
			($filteredBy ? ' &mdash; ' : '') .
			ucwords(str_replace('_', ' ', str_replace('_id', ' ', $filter))) .
			': ' .
			$value;
	}
}
echo "<b style='color: #464646'>";
if(isset($this->drillheading[0]) && !empty($this->drillheading[0])) echo implode(', ' , $this->drillheading).", ";
if(!empty($this->subvalue)){
    if( is_numeric($this->subvalue))
    {   
        echo $setting->getValue($this->subvalue);
    }
    else{
        if($this->subvalue =='Totals'){
            echo "Totals"; 

        }
        else{
            $ert = explode(',',$this->subvalue);

            $sdf = '';
            foreach( $ert as $er){
                $sdf .= $setting->getValue($er).' & '; 
            }
            echo substr($sdf,0,-2);
        }
    }
}
else{ 
    echo 'Uncoded'; 
} 
echo "</b><br>";

echo $filteredByLabel . $filteredBy;
?>
</div>

<div>

<table class="display">
	<thead>
	<tr class="count-hdr">		
			<th class="sort sorting<?=(isset($sorts['event_name']) && $sorts['event_name'] ? '_' . strtolower($sorts['event_name']) : '')?>">Event Name</th>
			<th class="sort sorting<?=(isset($sorts['organization_name']) && $sorts['organization_name'] ? '_' . strtolower($sorts['organization_name']) : '')?>">Organization</th>
			<th class="sort sorting<?=(isset($sorts['site']) && $sorts['site'] ? '_' . strtolower($sorts['site']) : '')?>">Site</th>
			<th class="sort sorting<?=(isset($sorts['outreach_type']) && $sorts['outreach_type'] ? '_' . strtolower($sorts['outreach_type']) : '')?>">Outreach Type</th>
			<th class="sort sorting<?=(isset($sorts['event_type']) && $sorts['event_type'] ? '_' . strtolower($sorts['event_type']) : '')?>">Event Type</th>
			<th class="sort sorting<?=(isset($sorts['hmgworker']) && $sorts['hmgworker'] ? '_' . strtolower($sorts['hmgworker']) : '')?>">HMG Worker</th>		
	</tr>
	</thead>
	<tbody>
<? $row = 'odd'; ?>

<? $organizationObj = $organization; ?>
	<? foreach($organizations as $organization) : ?>

		<tr id="organization_<?=$organization['organization_sites_id']?>_<?=$pos?>" class="organization <?=$row?>">
			<td><?=$organization['event_name']?></td>
			<td><a class="childLinks" href="index.php?action=organization&id=<?=$organization['organization_sites_id'] ?>"><?=$organization['organization_name']?></a></td>
			<td><?=isset($organization['site']) ? $organization['site'] : ''?></td>
			<td><?= $organization['outreach_type']?></td>			
			<td><?=$organization['event_type'] ?></td>
			<td><?=$organization['hmgworker']?></td>
		</tr>

		<? if($row=='odd'){ $row = 'even'; } else { $row='odd'; }?>
		
	<? endforeach; ?>
	</tbody>
</table>
<br />

<div class="gridFooter">
	<div style="float: left;" id="gridPaginationText">
		Showing <?= $firstRecord ?>-<?= $firstRecord+count($organizations)-1 ?> of  <?= $totalOrganizations ?> organizations
	</div>
	<div style="float: right;" id="gridPages">
		<a href="index.php?action=counts&type=eventsDrill&substatus=<?=$substatus ?>&page=1&<?php echo ($field ? '&subvalue='.$field : '');  ?>">First</a>		
		<?= ($pageNumber > 1 ? '<a href="index.php?action=counts&type=eventsDrill&substatus='.$substatus.'&subvalue=' . ($field ? '&subvalue=' . $field : '')  . ($search ? '&search=' . $search : '') . '&page= ' . ($pageNumber - 1) . '">&lt; Prev</a>' : '')?>
		Page <?= $pageNumber ?> of <?= $numPages ?>
		<?= ($pageNumber < $numPages ? '<a href="index.php?action=counts&type=eventsDrill&substatus='.$substatus.'&subvalue=' . ($field ? '&subvalue='.$field : '') . '&page= ' . ($pageNumber + 1) . ($search ? '&search=' . $search : '') . '">Next &gt;</a>' : '')?>
		<a href="index.php?action=counts&type=eventsDrill&substatus=<?=$substatus ?>&subvalue=<?= ($field ? '&subvalue='.$field : '') ?>&page=<?= $numPages ?>">Last</a>
		
	</div>
</div>
<?php
?>
</div>
<? include_once(VIEW_PATH . '/counts-advanced-search.phtml');

