<?php 
//echo "<pre>";print_r($_SERVER);die;
function buildUrl($new) {
	$scheme = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' ? 'https' : 'http';
	$url = $scheme.'://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
	if(empty($scheme) && isset($_SERVER['REQUEST_SCHEME'])) {
		$url = $_SERVER['REQUEST_SCHEME'].'://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
	}

	$url_parts = parse_url($url);
	parse_str($url_parts['query'], $params);

	$params[$new] = true;     // Overwrite if exists
	// Note that this will url_encode all values
	$url_parts['query'] = http_build_query($params);

	// If not
	return $url_parts['scheme'] . '://' . $url_parts['host'] . $url_parts['path'] . '?' . $url_parts['query'];
}
$urlPrint  = buildUrl('print');
$urlExport = buildUrl('export');

?>

<script>
$(function(){

	$('.fancybox').fancybox({
		padding : '0px', scrolling : 'no'
	});

	$(document).on('click', '#print-list', function(e){
		e.preventDefault();
		postString = $('#filter-form').serialize();
		window.open('<?php echo $urlPrint?>');
		//window.open('index.php?print=true&' + postString, '');
	});
	$(document).on('click', '#export-list', function(e){
		e.preventDefault();
		postString = $('#filter-form').serialize();
		
		window.open('<?php echo $urlExport?>');

	});
	$(".sort").on("click", function(){
		field = ($(this).text().replace(/ /g, '_').toLowerCase());
		if($(this).hasClass('sorting_asc')){
			$(this).removeClass('sorting_asc').addClass('sorting_desc');
			fieldsort = 'desc';
		}
		else if($(this).hasClass('sorting_desc')){
			$(this).removeClass('sorting_desc').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		else {
			$(this).removeClass('sorting').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		if(field == 'reason_for_call'){
			field = 'call_reason';
		}
		if(field == 'phone'){
			field = 'primary_phone';
		}
		location.href="index.php?action=counts&type=familyDrill&field="+field+"&sort="+fieldsort<?= ($search ? '+"&search=' . $search . '"' : '')?><?= (isset($this->drillName) ? '+"&drillName=' . $this->drillName . '"' : '')?><?= (isset($this->status) ? '+"&status=' . $this->status . '"' : '')?>;
	});
	/*
	$('th.sort').click(function(){
		if($(this).hasClass('sorting_asc')){
			$(this).removeClass('sorting_asc').addClass('sorting_desc');
		}
		else {
			$(this).removeClass('sorting_desc').addClass('sorting_asc');
		}
	    var table = $(this).parents('table').eq(0)
	    var lastRow = table.find('tr:last');
	    lastRowLabel = lastRow.find('td:first').text();
	    if(lastRowLabel == 'Total' || lastRowLabel == 'Totals'){
	    	lastRow.remove();
	    }
	    var rows = table.find('tr:gt(0)').toArray().sort(comparer($(this).index()))
	    this.asc = !this.asc
	    if (this.asc){rows = rows.reverse()}
	    for (var i = 0; i < rows.length; i++){table.append(rows[i])}
	    if(lastRowLabel == 'Total' || lastRowLabel == 'Totals'){
	   		table.append(lastRow);
	   	}
	   	// Fix odd/event class on sorted elements
	   	rowClass = 'even';
	   	table.find('tr:gt(0)').each(function(index){
	   		curRow = $(this);
	   		curRow.attr('class', rowClass);
	   		if(rowClass == 'even'){
	   			rowClass = 'odd';
	   		} else {
	   			rowClass = 'even';
	   		}
	   	});
	});*/
	function comparer(index) {
	    return function(a, b) {
	        var valA = getCellValue(a, index), valB = getCellValue(b, index)
	        return $.isNumeric(valA) && $.isNumeric(valB) ? valA - valB : valA.localeCompare(valB)
	    }
	}
	function getCellValue(row, index){ return $(row).children('td').eq(index).html() }

	$('#multi-zip').on('change', function(e){
		var checkbox = this;
		$('.select').attr('multiple',checkbox.checked);
	 	if(checkbox.checked){
	 		$('.select').attr('name','filters[zip][]');
	 		$('.select').attr('size','11');
	 	} else {
	 		$('.select').attr('name','filters[zip]');
	 		$('.select').attr('size','1');
	 	}
	});

	$('.date').datepicker();
});
</script>
<div class="pageTitleBar">
	<a href="index.php?action=counts"><h1>Family Demographics</h1></a>

	<div style="float: right; padding: 0px 4px 4px 0; margin-left: 10px;">
		<form id="filter-form" action="index.php" style="padding: 8px 3px 0 4px;">
			<input type="hidden" name="action" value="counts">
			<input type="hidden" id="count-family" name="type" value="familyDrill">
			<input type="hidden" name="drillheading" value="<?php echo isset($_REQUEST['drillheading']) ? $_REQUEST['drillheading'] : ''?>">
			<div style="float: right; margin-left: 60px">
			<input type="submit" class="btn-small" id="export-list" name="export_list" value="Export" />
			<input type="submit" class="btn-small" id="print-list" name="export_list" value="Print" />
			<input type="submit" class="btn-small" value="Counts" onclick="$('#count-family').val(0);" />
			
			</div>
			<style>
			select.status{
				width: auto;
			}
			.pageTitleBar input[type="text"] {
				width: 80px;
			}
			.school_district, .select, .filter {
				display: inline-block;
				float: left;
				margin-right: 2px;
				margin-top: 2px;
			}
			.counts-county{
				float: left;
				margin-right: 2px;
				margin-top: 2px;
			}
			.select-wrapper {
				float: left;
				margin-right: 20px;
			}
			.filter-container {
				float: left;
				margin: auto 0;
			}
			#multi-zip{
				vertical-align: middle;
			}
			a.familyLinks { color: #464646; text-decoration: none; }
			a.familyLinks:hover { text-decoration: underline; }
			a.childLinks { color: #464646; text-decoration: none; }
			a.childLinks:hover { text-decoration: underline; }
			</style>
			<div class="filter-container">
				<?= $region->displaySelect('filters[region_id]', $filters['region_id'], 'Region', false, null, 'filter') ?>
				<?//= $county->displaySelect('filters[county]', $filters['county'], 'County', '', false, ' counts-county', false) ?>
				<?// if(is_array($filters['zip'])){ $multiSelect = true; } else { $multiSelect = false; } $tabIndex = ''; ?>
				<?//= $schoolDistrict->displaySelect('filters[school_district]', $filters['school_district'], 'School District') ?><?php /*
				<div class="select-wrapper">
					<?= $family->displayFieldSelect('filters[zip]', 'zip', $filters['zip'], 'Zip Code', $tabIndex, $multiSelect) 
				</div>
				
				Multi <input id="multi-zip" type="checkbox" <?= ($multiSelect ? ' checked' : ''); ?> />
				*/?>
				<?= $status->displaySelect('filters[status]', $filters['status'], 'Status', '', false, ' counts-status', false) ?>
				<input type="text" class="date" id="start-date" name="filters[start_date]" value="<?= $filters['start_date'] ?>" placeholder="Start Date" />
				<input type="text" class="date" id="end-date" name="filters[end_date]" value="<?= $filters['end_date'] ?>" placeholder = "End Date" />
				<input type="submit" value="Filter" class="btn-small" />  <input type="submit" name="clearFilters" value="Clear" class="btn-small" />

			</div>
			<a href="#counts-advanced-search" class="fancybox" style="font-size: 10px !important; line-height: 10px; font-weight: bold; display: inline-block; margin-left: 10px; text-align: center;">Advanced<br /> Search</a>
		</form>
	</div>
</div>

<div style="width: 100%; margin-bottom: 5px; clear: both;">
<?
$filteredByLabel = '';
$filteredBy = '';
if(count($filters)){
	$filteredByLabel = '<b style="color: #464646">Active Filters: </b>';
}
foreach($filters as $filter => $value){
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter != 'zip' && $filter != 'school_district'){
		$value = $setting->getValue($value);
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter == 'school_district'){
		$value = $schoolDistrict->getSchoolDistrictById($value);
	}
	if($value){
		if(is_array($value)){
			$value = implode($value, ', ');
		}
		$filteredBy .=
			($filteredBy ? ' &mdash; ' : '') .
			ucwords(str_replace('_', ' ', str_replace('_id', ' ', $filter))) .
			': ' .
			$value;
	}
}
if(isset($this->drillheading[0]) && !empty($this->drillheading[0])) echo "<b style='color: #464646'>".implode(', ' , $this->drillheading)."</b><br>";
echo $filteredByLabel . $filteredBy;
?>
</div>

<div>

<table class="display">
	<thead>
	<tr class="count-hdr">
		<th class="sort sorting<?=(isset($sorts['primary_contact']) && $sorts['primary_contact'] ? '_' . strtolower($sorts['primary_contact']) : '')?>">Primary Contact</th>
		<th class="sort sorting<?=(isset($sorts['language']) && $sorts['language'] ? '_' . strtolower($sorts['language']) : '')?>">Language</th>
		<th class="sort sorting<?=(isset($sorts['city']) && $sorts['city'] ? '_' . strtolower($sorts['city']) : '')?>">City</th>
		<th class="sort sorting<?=(isset($sorts['status']) && $sorts['status'] ? '_' . strtolower($sorts['status']) : '')?>">Status</th>
		<th class="sort sorting<?=(isset($sorts['hmg_worker']) && $sorts['hmg_worker'] ? '_' . strtolower($sorts['hmg_worker']) : '')?>">HMG Worker</th>
	</tr>
	</thead>
	<tbody>
<? $class = 'odd'; ?>

<? foreach($familydetails as $row): ?>
<? $class = ($class == 'even' ? 'odd' : 'even') ?>
	<tr class="<?= $class ?>">
		<td class="center">
			<a class="childLinks" href="index.php?action=family&id=<?php echo $row['id']; ?>&pos=0"><?= $row['first_name_1'] .' '. $row['last_name_1'] ?></a>
		</td>
		<td class="center"><?= $row['language'] ?></td>
		<td class="center"><?= $row['city'] ?></td>
		<td class="center"><?= $row['status'] ?></td>
		<td class="center"><?= $row['hmg_worker'] ?></td>

	</tr>
<? endforeach ?>
	</tbody>
</table>
<br />

<div class="gridFooter">
	<div style="float: left;" id="gridPaginationText">
		Showing <?= $firstRecord ?>-<?= $lastRecord ?> of  <?= $totalfamilies ?> families
	</div>
	<div style="float: right;" id="gridPages">
		<a href="index.php?action=counts&type=familyDrill&page=1&<?php echo ($field ? '&status='.$field : '');  ?>">First</a>
		
		<?= ($pageNumber > 1 ? '<a href="index.php?action=counts&type=familyDrill&status=' . ($field ? '&status=' . $field : '')  . ($search ? '&search=' . $search : '') . '&page= ' . ($pageNumber - 1) . '">&lt; Prev</a>' : '')?>
		Page <?= $pageNumber ?> of <?= $numPages ?>
		<?= ($pageNumber < $numPages ? '<a href="index.php?action=counts&type=familyDrill&status=' . ($field ? '&status='.$field : '') . '&page= ' . ($pageNumber + 1) . ($search ? '&search=' . $search : '') . '">Next &gt;</a>' : '')?>
		<a href="index.php?action=counts&type=familyDrill&status=<?= ($field ? '&status='.$field : '') ?>&page=<?= $numPages ?>">Last</a>
		
	</div>
</div>
<?php
 

	

?>
</div>
<? include_once(VIEW_PATH . '/counts-advanced-search.phtml');

