<div class="pageTitleBar">
	<a href="index.php?action=counts"><h1>Common Indicators</h1></a>
</div>

<style>
#count-links a {
	font-size: 10pt;
	line-height: 18pt;
	color: #000;
}
</style>
<div id="count-links">
<a href="index.php?action=counts&type=indicators demographics">Help Me Grow Demographics</a><br>
<a href="index.php?action=counts&type=indicators nature issues">Nature of Presenting Issues/Concerns</a><br>
<a href="index.php?action=counts&type=indicators program referrals">Referrals by Help Me Grow to Service Programs</a><br>
<a href="index.php?action=counts&type=indicators outcome">Help Me Grow Outcome</a>
</div>

