<script>
$(function(){
	$('th.sort').click(function(){
		if($(this).hasClass('sorting_asc')){
			$(this).removeClass('sorting_asc').addClass('sorting_desc');
		}
		else {
			$(this).removeClass('sorting_desc').addClass('sorting_asc');
		} 
	    var table = $(this).parents('table').eq(0)
	    var lastRow = table.find('tr:last');
	    lastRowLabel = lastRow.find('td:first').text();
	    if(lastRowLabel == 'Total' || lastRowLabel == 'Totals'){
	    	lastRow.remove();
	    }
	    var rows = table.find('tr:gt(0)').toArray().sort(comparer($(this).index()))
	    this.asc = !this.asc
	    if (this.asc){rows = rows.reverse()}
	    for (var i = 0; i < rows.length; i++){table.append(rows[i])}
	    if(lastRowLabel == 'Total' || lastRowLabel == 'Totals'){
	   		table.append(lastRow);
	   	}
	});
	function comparer(index) {
	    return function(a, b) {
	        var valA = getCellValue(a, index), valB = getCellValue(b, index)
	        console.log('a: ' + parseInt(valA) + ' b: ' + valB)
	        return ($.isNumeric(valA) && $.isNumeric(valB)) ? valA - valB : valA.localeCompare(valB)
	    }
	}
	function getCellValue(row, index){ 
		var text = $(row).children('td').eq(index).text(); 
		if(text.indexOf('month') !== -1){ 
			text = parseInt(text) 
		} else if(text.indexOf('Uncoded') !== -1){ 
			text = 1000; 
		} 
		return text;
	}
});
</script>

<? 

$filteredByLabel = '';
$filteredBy = '';
if(count($filters)){
	$filteredByLabel = '<b style="color: #464646">Active Filters: </b>';
}
foreach($filters as $filter => $value){
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter != 'zip' && $filter != 'school_district'){
		$value = $setting->getValue($value);
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter == 'school_district'){
		$value = $schoolDistrict->getSchoolDistrictById($value);
	}
	if($value){
		if(is_array($value)){
			$value = implode($value, ', ');
		}
		$filteredBy .=
			($filteredBy ? ' &mdash; ' : '') .
			ucwords(str_replace('_', ' ', str_replace('_id', ' ', $filter))) . 
			': ' . 
			$value;
	}
}
?>

<?= $headerHtml ?>
<div class="filters" style="padding-bottom: 3px;"><?= $filteredByLabel . $filteredBy ?></div>

<div id="counts-column1">

<table class="display">
	<thead>
	<tr class="count-hdr">
		<th class="sort sorting_asc">Number of Screenings</th>
		<th class="sort sorting_asc">Count</th>
		<th class="center">Pct%</th>
	</tr>
	</thead>
	<tbody>
<? $class = 'odd'; ?>
<? foreach($screeningsCounts as $row): ?>
<? $class = ($class == 'even' ? 'odd' : 'even') ?>
	<tr class="<?= $class ?>">
		<td><?= (!is_null($row['name']) ? $row['name'] : 'Uncoded') ?></td>
		<td class="center"><?= $row['cnt'] ?></td>
		<td class="center"><?= $row['percent'] ?></td>
	</tr>
<? endforeach ?>
	</tbody>
</table>

<br />




</div>

<div id="counts-column2">

<table class="display">
	<thead>
	<tr class="count-hdr">
		<th class="sort sorting_asc">Screening Frequency</th>
		<th class="sort sorting_asc">Count</th>
		<th class="center">Pct%</th>
	</tr>
	</thead>
	<tbody>
<? $class = 'odd'; ?>
<? foreach($asqFrequencyCounts as $row): ?>
<? $class = ($class == 'even' ? 'odd' : 'even') ?>
	<tr class="<?= $class ?>">
		<td><?= (!empty($row['name']) ? $row['name'] : 'Uncoded') ?></td>
		<td class="center"><?= $row['cnt'] ?></td>
		<td class="center"><?= $row['percent'] ?></td>
	</tr>
<? endforeach ?>
	</tbody>
</table>

<br />

</div>

<div id="counts-column3">

<table class="display">
	<thead>
	<tr class="count-hdr">
		<th class="sort sorting_asc">Screening Interval</th>
		<th class="sort sorting_asc">Count</th>
		<th class="center">Pct%</th>
	</tr>
	</thead>
	<tbody>
<? $class = 'odd'; ?>
<? foreach($asqSeCounts as $row): ?>
<? $class = ($class == 'even' ? 'odd' : 'even') ?>
	<tr class="<?= $class ?>">
		<td><?= (!empty($row['name']) ? $row['name'] : 'Uncoded') ?></td>
		<td class="center"><?= $row['cnt'] ?></td>
		<td class="center"><?= $row['percent'] ?></td>
	</tr>
<? endforeach ?>
	</tbody>
</table>

<br />

</div>