<?php 
//echo "<pre>";print_r($_SERVER);die;
function buildUrl($new) {
	$scheme = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' ? 'https' : 'http';
	$url = $scheme.'://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
	if(empty($scheme) && isset($_SERVER['REQUEST_SCHEME'])) {
		$url = $_SERVER['REQUEST_SCHEME'].'://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
	}

	$url_parts = parse_url($url);
	parse_str($url_parts['query'], $params);

	$params[$new] = true;     // Overwrite if exists
	// Note that this will url_encode all values
	$url_parts['query'] = http_build_query($params);

	// If not
	return $url_parts['scheme'] . '://' . $url_parts['host'] . $url_parts['path'] . '?' . $url_parts['query'];
}
$urlPrint  = buildUrl('print');
$urlExport = buildUrl('export');
//echo "<pre>";print_r($sorts);echo "</pre>";
?>

<script>
$(function(){
	/*setTimeout(function() {
		$('table .count-hdr').find('th').eq(0).trigger('click');
		$('table .count-hdr').find('th').eq(0).trigger('click');
	}, 500);*/
	$('.fancybox').fancybox({
		padding : '0px', scrolling : 'no'
	});

	$(document).on('click', '#print-list', function(e){
		e.preventDefault();
		postString = '<?php echo $urlPrint; ?>';
		if(postString === undefined || postString == '') {
			postString = $('#filter-form').serialize();
			window.open('index.php?print=true&' + postString, '');
		} else {
			window.open(postString);
		}
	});
	$(document).on('click', '#export-list', function(e){
		e.preventDefault();
		postString = '<?php echo $urlExport; ?>';
		if(postString === undefined || postString == '') {
			postString = $('#filter-form').serialize();
			window.open('index.php?export=true&' + postString, '');
		} else {
			window.open(postString);
		}
	});

	function comparer(index) {
	    return function(a, b) {
	        var valA = getCellValue(a, index), valB = getCellValue(b, index)
	        return ($.isNumeric(valA) && $.isNumeric(valB)) ? valA - valB : valA.localeCompare(valB)
	    }
	}
	function getCellValue(row, index){
		var text = $(row).children('td').eq(index).text();
		if(text.indexOf('referrals') !== -1){
			text = parseInt(text)
		} else if(text.indexOf('Uncoded') !== -1){
			text = 1000;
		}
		return text;
	}

	$(".sort").on("click", function(){
		field = ($(this).text().replace(/ /g, '_').toLowerCase());
		if($(this).hasClass('sorting_asc')){
			$(this).removeClass('sorting_asc').addClass('sorting_desc');
			fieldsort = 'desc';
		}
		else if($(this).hasClass('sorting_desc')){
			$(this).removeClass('sorting_desc').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		else {
			$(this).removeClass('sorting').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		if(field == 'reason_for_call'){
			field = 'call_reason';
		}
		if(field == 'phone'){
			field = 'primary_phone';
		}
		location.href="index.php?action=counts&type=screeningsDrill&field="+field+"&sort="+fieldsort<?= ($search ? '+"&search=' . $search . '"' : '')?><?= (isset($_SESSION['drillName']) ? '+"&drillName=' . $_SESSION['drillName'] . '"' : '')?>;
	});

	$('#multi-zip').on('change', function(e){
		var checkbox = this;
		$('.select').attr('multiple',checkbox.checked);
	 	if(checkbox.checked){
	 		$('.select').attr('name','filters[zip][]');
	 		$('.select').attr('size','11');
	 	} else {
	 		$('.select').attr('name','filters[zip]');
	 		$('.select').attr('size','1');
	 	}
	});

	$('.date').datepicker();
	
});
</script>
<div class="pageTitleBar">
	<a href="index.php?action=counts"><h1>Child Demographics</h1></a>
	<div style="float: right; padding: 0px 4px 4px 0; margin-left: 20px;">
		<form id="filter-form" action="index.php" style="padding: 8px 3px 0 4px;">
			<input type="hidden" name="action" value="counts">
			<input type="hidden" id="count-family" name="type" value="screeningsDrill">
			<div style="float: right; margin-left: 60px;">
				<input type="submit" class="btn-small" id="export-list" name="export_list" value="Export" />
				<input type="submit" class="btn-small" id="print-list" name="print_list" value="Print" />
				<input type="submit" class="btn-small" value="Counts" onclick="$('#count-family').val(0);" />

				<a name="Back" onclick="location.href='index.php?action=counts&type=screenings'" class="btn-small">Back</a>
			</div>
			<style>
			select.status{
				width: auto;
			}
			.pageTitleBar input[type="text"] {
				width: 80px;
			}
			.school_district, .select, .filter {
				display: inline-block;
				float: left;
				margin-right: 2px;
				margin-top: 2px;
			}
			.counts-county{
				float: left;
				margin-right: 2px;
				margin-top: 2px;
			}
			.select-wrapper {
				float: left;
				margin-right: 20px;
			}
			.filter-container {
				float: left;
				margin: auto 0;
			}
			#multi-zip{
				vertical-align: middle;
			}
			a.childLinks { color: #464646; text-decoration: none; }
			a.childLinks:hover { text-decoration: underline; }
			a.btn-small {
				background: #ccc none repeat scroll 0 0 !important;
			    border: 2px outset #998997 !important;
			    border-radius: 7px;
			    color: #555 !important;
			    cursor: pointer;
			    font: bold 12px/12px arial,helvetica,san-serif !important;
			    padding: 3px 6px;
			    text-decoration: none;
			}
			</style>
			<div class="filter-container">
				<?= $region->displaySelect('filters[region_id]', $filters['region_id'], 'Region', false, null, 'filter') ?>
				<?= $status->displaySelect('filters[status]', $filters['status'], 'Status', '', false, ' counts-status', false) ?>
				<input type="text" class="date" id="start-date" name="filters[start_date]" value="<?= $filters['start_date'] ?>" placeholder="Start Date" />
				<input type="text" class="date" id="end-date" name="filters[end_date]" value="<?= $filters['end_date'] ?>" placeholder = "End Date" />
				<input type="submit" value="Filter" class="btn-small" />  <input type="submit" name="clearFilters" value="Clear" class="btn-small" />

			</div>
			<a href="#counts-advanced-search" class="fancybox" style="font-size: 10px !important; line-height: 10px; font-weight: bold; display: inline-block; margin-left: 10px; text-align: center;">Advanced<br /> Search</a>
		</form>
	</div>
</div>

<div class="row">
<div style="width: 100%; margin-bottom: 5px; clear: both;">
<?

$filteredByLabel = '';
$filteredBy = '';
if(count($filters)){
	$filteredByLabel = '<b style="color: #464646">Active Filters: </b>';
}
foreach($filters as $filter => $value){
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter != 'zip' && $filter != 'school_district'){
		$value = $setting->getValue($value);
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter == 'school_district'){
		$value = $schoolDistrict->getSchoolDistrictById($value);
	}
	if($value){
		if(is_array($value)){
			$value = implode($value, ', ');
		}
		$filteredBy .=
			($filteredBy ? ' &mdash; ' : '') .
			ucwords(str_replace('_', ' ', str_replace('_id', ' ', $filter))) .
			': ' .
			$value;
	}
}
if(isset($this->drillheading[0]) && !empty($this->drillheading[0])) echo "<b style='color: #464646'>".implode(', ' , $this->drillheading)."</b><br>";
echo $filteredByLabel . $filteredBy;
?>
</div>
<table class="display">
	<thead>
	<tr class="count-hdr">
		<th class="sort sorting<?=(isset($sorts['child_name']) && $sorts['child_name'] ? '_' . strtolower($sorts['child_name']) : '')?>">Child Name</th>
		<th class="sort sorting<?=(isset($sorts['birthdate']) && $sorts['birthdate'] ? '_' . strtolower($sorts['birthdate']) : '')?>">Birthdate</th>
		<th class="sort sorting<?=(isset($sorts['screening_type']) && $sorts['screening_type'] ? '_' . strtolower($sorts['screening_type']) : '')?>">Screening Type</th>
		<th class="sort sorting<?=(isset($sorts['screening_interval']) && $sorts['screening_interval'] ? '_' . strtolower($sorts['screening_interval']) : '')?>">Screening Interval</th>
		<th class="sort sorting<?=(isset($sorts['screening_score']) && $sorts['screening_score'] ? '_' . strtolower($sorts['screening_score']) : '')?>">Screening Score</th>
		<th class="sort sorting<?=(isset($sorts['status']) && $sorts['status'] ? '_' . strtolower($sorts['status']) : '')?>">Status</th>
		<th class="sort sorting<?=(isset($sorts['hmg_worker']) && $sorts['hmg_worker'] ? '_' . strtolower($sorts['hmg_worker']) : '')?>">HMG Worker</th>
	</tr>
	</thead>
	<tbody>
<? $class = 'odd'; //echo "<pre>";print_r($childDetails);
	/*function aasort (&$array, $key) {
	    $sorter=array();
	    $ret=array();
	    reset($array);
	    foreach ($array as $ii => $va) {
	        $sorter[$ii]=$va[$key];
	    }
	    asort($sorter);
	    foreach ($sorter as $ii => $va) {
	        $ret[$ii]=$array[$ii];
	    }
	    $array=$ret;
	}
	aasort($childDetails,"first");*/
	//echo "<pre>";print_r($childDetails);
?>
<? foreach($childDetails as $row): ?>
<? $class = ($class == 'even' ? 'odd' : 'even') ?>
	<tr class="<?= $class ?>">
		<td><a class="childLinks" href="index.php?action=child&child_id=<?php echo $row['id']; ?>&pos=0"><?= $row['first'].' '.$row['last'] ?></a></td>
		<td class="center"><?= date('m/d/Y', strtotime($row['birth_date'])) ?></td>
		<td class="center"><?= $row['type']; //261016 revert back ?></td>
		<td class="center"><?= ($row['asq_month'] > 0) ? $row['asq_month'] .' months' : $row['asq_month']; ?></td>
		<td class="center"><?= $row['score'] ?></td>
		<td class="center">
			<?= $row['fstatus'] ?>
		</td>
		<td>
			<?= $row['hmg_worker'] ?>
		</td>
	</tr>
<? endforeach ?>
	</tbody>
</table>

</div>

<div class="gridFooter">
	<div style="float: left;" id="gridPaginationText">
		Showing <?= $firstRecord ?>-<?= $lastRecord ?> of  <?= $totalChilds ?> childs
	</div>
	<div style="float: right;" id="gridPages">
		<a href="index.php?action=counts&type=screeningsDrill"<?php echo ($field ? '&status='.$field : ''); echo ($issues ? '&issues=' . $issues : ''); echo ($county ? '&county=' . $county : ''); ?>>First</a>
		
		<?= ($pageNumber > 1 ? '<a href="index.php?action=counts&type=screeningsDrill' . ($field ? '&status=' . $field : '')  . ($search ? '&search=' . $search : '') . ($issues ? '&issues=' . $issues : '') .($county ? '&county=' . $county : '') . '&page= ' . ($pageNumber - 1) . '">&lt; Prev</a>' : '')?>
		Page <?= $pageNumber ?> of <?= $numPages ?>
		<?= ($pageNumber < $numPages ? '<a href="index.php?action=counts&type=screeningsDrill' . ($field ? '&status='.$field : '') . '&page= ' . ($pageNumber + 1) . ($search ? '&search=' . $search : '') .($issues ? '&issues=' . $issues : '') .($county ? '&county=' . $county : ''). '">Next &gt;</a>' : '')?>
		<a href="index.php?action=counts&type=screeningsDrill<?= ($field ? '&status='.$field : '').($issues ? '&issues=' . $issues : '') .($county ? '&county=' . $county : '') ?>&page=<?= $numPages ?>">Last</a>
		
	</div>
</div>



<? include_once(VIEW_PATH . '/counts-advanced-search.phtml');



