<div class="pageTitleBar">
	<h1>Counts</h1>
</div>
<style>
#count-links a {
	font-size: 10pt;
	line-height: 18pt;
	color: #000;
}
</style>
<div id="count-links">
<!-- <a href="index.php?action=counts&type=program">Program Information</a><br> -->
<a href="index.php?action=counts&type=family&clearFilters=Clear">Family Demographics</a><br>
<a href="index.php?action=counts&type=familyscreenings&clearFilters=Clear">Family Screenings</a><br>
<a href="index.php?action=counts&type=child&clearFilters=Clear">Child Demographics</a><br>
<a href="index.php?action=counts&type=screenings">Developmental Screenings</a><br>
<a href="index.php?action=counts&type=referrals">Outgoing Referrals</a><br>
<a href="index.php?action=counts&type=organization">Organization Demographics</a><br>
<a href="index.php?action=counts&type=outreach_events">Outreach Events</a><br>
<a href="index.php?action=counts&type=accesspoint">Central Access Point</a><br>
<a href="index.php?action=counts&type=volunteer">Volunteer Information</a><br>
<a href="index.php?action=counts&type=provider">Provider Information</a><br>
<a href="index.php?action=counts&type=indicators">Common Indicators</a>
</div>

