<? 
$csv = "Counts: Indicators Program Referrals\n\n";

$encapsulateField = false;
$filteredByLabel = '';
$filteredBy = '';
if(count($filters)){
	$filteredByLabel = 'Active Filters: ';
}
foreach($filters as $filter => $value){
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter != 'zip' && $filter != 'school_district'){
		$value = $setting->getValue($value);
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter == 'school_district'){
		$value = $schoolDistrict->getSchoolDistrictById($value);
	}
	if($value){
		if(is_array($value)){
			$value = implode($value, ', ');
			$encapsulateField = true;
		}
		$filteredBy .=
			($filteredBy ? ' - ' : '') .
			ucwords(str_replace('_', ' ', str_replace('_id', ' ', $filter))) . 
			': ' . 
			$value;
	}
}
if($encapsulateField){
	$csv .= '"' . $filteredByLabel . $filteredBy . '",,';
} else {
	$csv .= $filteredByLabel . $filteredBy . ',,';
}

if($filteredByLabel){
	$csv .= "\n\n";
} else {
	$csv .= "\n";
}

$csv .= 'Types of Service,Count,Pct%' . "\n";
foreach($referralServiceCounts as $row){
	$row['name'] = strpos($row['name'], ',') ? '"' . $row['name'] . '"' : $row['name'];
	$csv .= (!empty($row['name']) ? $row['name'] : 'Uncoded') . ',';
	$csv .= $row['cnt'] . ',';
	$csv .= $row['percent'] . "\n";
}

$csv .= "\n" . 'Gaps,Count,Pct%' . "\n";
foreach($gapCounts as $row){
	$row['name'] = strpos($row['name'], ',') ? '"' . $row['name'] . '"' : $row['name'];
	$csv .= (!empty($row['name']) ? $row['name'] : 'Uncoded') . ',';
	$csv .= $row['cnt'] . ',';
	$csv .= $row['percent'] . "\n";
}

$csv .= "\n" . 'Barriers,Count,Pct%' . "\n";
foreach($barrierCounts as $row){
	$row['name'] = strpos($row['name'], ',') ? '"' . $row['name'] . '"' : $row['name'];
	$csv .= (!empty($row['name']) ? $row['name'] : 'Uncoded') . ',';
	$csv .= $row['cnt'] . ',';
	$csv .= $row['percent'] . "\n";
}

echo $csv;
?>

					                         
