<? 
$csv = "Counts: Call Reason Demographics\n\n";

if(isset($this->drillheading[0]) && !empty($this->drillheading[0])) $csv .=  implode(' - ' , $this->drillheading)."\n\n";

$encapsulateField = false;
$filteredByLabel = '';
$filteredBy = '';
if(count($filters)){
	$filteredByLabel = 'Active Filters: ';
}
foreach($filters as $filter => $value){
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter != 'zip' && $filter != 'school_district'){
		$value = $setting->getValue($value);
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter == 'school_district'){
		$value = $schoolDistrict->getSchoolDistrictById($value);
	}
	if($value){
		if(is_array($value)){
			$value = implode($value, ', ');
			$encapsulateField = true;
		}
		$filteredBy .=
			($filteredBy ? ' - ' : '') .
			ucwords(str_replace('_', ' ', str_replace('_id', ' ', $filter))) . 
			': ' . 
			$value;
	}
}
if($encapsulateField){
	$csv .= '"' . $filteredByLabel . $filteredBy . '",,';
} else {
	$csv .= $filteredByLabel . $filteredBy . ',,';
}


if($filteredByLabel){
	$csv .= "\n\n";
} else {
	$csv .= "\n";
}

$csv .= 'Primary Contact,Language,City,Status,HMG Worker' . "\n";
foreach($calldetails as $row){
	
	$csv .= $row['first_name_1']." ".$row['last_name_1'].',';
	$csv .= $row['language'] . ',';
	$csv .= $row['city']. ',';
	$csv .= $row['status']. ',';
	$csv .= $row['hmg_worker']. ','. "\n";
}

echo $csv;
?>