<? 
$csv = "Counts: Developmental Screening Demographics\n\n";

if(isset($this->drillheading[0]) && !empty($this->drillheading[0])) $csv .=  implode(' - ' , $this->drillheading)."\n\n";

$encapsulateField = false;
$filteredByLabel = '';
$filteredBy = '';
if(count($filters)){
	$filteredByLabel = 'Active Filters: ';
}
foreach($filters as $filter => $value){
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter != 'zip' && $filter != 'school_district'){
		$value = $setting->getValue($value);
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter == 'school_district'){
		$value = $schoolDistrict->getSchoolDistrictById($value);
	}
	if($value){
		if(is_array($value)){
			$value = implode($value, ', ');
			$encapsulateField = true;
		}
		$filteredBy .=
			($filteredBy ? ' - ' : '') .
			ucwords(str_replace('_', ' ', str_replace('_id', ' ', $filter))) . 
			': ' . 
			$value;
	}
}
if($encapsulateField){
	$csv .= '"' . $filteredByLabel . $filteredBy . '",,';
} else {
	$csv .= $filteredByLabel . $filteredBy . ',,';
}

if($filteredByLabel){
	$csv .= "\n\n";
} else {
	$csv .= "\n";
}

$csv .= 'Child Name,Birthdate,Screening Type,Screening Interval,Screening Score,Status,HMG Worker' . "\n";
foreach($childDetails as $row){
	$daysInCurrentMonth = date('t');
	//$d1 = new DateTime('yesterday');
	$d1 = new DateTime();
	$d2 = new DateTime($row['birth_date']);

	
	$csv .= str_replace(',', '.', $row['first']).' '.str_replace(',', '.', $row['last']).',';
	$csv .= date('m/d/Y', strtotime($row['birth_date'])) . ',';
	$csv .= $row['type'] . ','; //261016 revert back
	$csv .= (($row['asq_month'] > 0) ? $row['asq_month'] .' months' : $row['asq_month']).' ,';
	$csv .= $row['score'] . ',';
	$csv .= $row['fstatus'] . ',';
	$csv .= str_replace(',', '.', $row['hmg_worker']) . "\n";
}

echo $csv;
?>

					                         
