<? 
$csv = "Counts: Child Demographics\n\n";

if(isset($this->drillheading[0]) && !empty($this->drillheading[0])) $csv .=  implode(' - ' , $this->drillheading)."\n\n";

$encapsulateField = false;
$filteredByLabel = '';
$filteredBy = '';
if(count($filters)){
	$filteredByLabel = 'Active Filters: ';
}
foreach($filters as $filter => $value){
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter != 'zip' && $filter != 'school_district'){
		$value = $setting->getValue($value);
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter == 'school_district'){
		$value = $schoolDistrict->getSchoolDistrictById($value);
	}
	if($value){
		if(is_array($value)){
			$value = implode($value, ', ');
			$encapsulateField = true;
		}
		$filteredBy .=
			($filteredBy ? ' - ' : '') .
			ucwords(str_replace('_', ' ', str_replace('_id', ' ', $filter))) . 
			': ' . 
			$value;
	}
}
if($encapsulateField){
	$csv .= '"' . $filteredByLabel . $filteredBy . '",,';
} else {
	$csv .= $filteredByLabel . $filteredBy . ',,';
}

if($filteredByLabel){
	$csv .= "\n\n";
} else {
	$csv .= "\n";
}

$csv .= 'Child,Gender,Birthdate,Age,Primary Contact,Status,HMG Worker' . "\n";
foreach($childDetails as $row){
	$daysInCurrentMonth = date('t');
	//$d1 = new DateTime('yesterday');
	$d1 = new DateTime();
	$d2 = new DateTime($row['birth_date']);

	$txt = '';
	$adjustedDate = date('M d, Y', strtotime($row['early'] . ' weeks ago', strtotime('yesterday')));
	$d3 = new DateTime($adjustedDate);
	$earlyInterval = $d3->diff($d2);
	$interval = $d1->diff($d2);
	$unborn = false;
	if(strtotime($row['birth_date']) > time()){
		$unborn = true;
	}
	$years = $interval->format("%y");
	$months = $interval->format("%m");
	$days = $interval->format("%d");

	$totalMonths = $years * 12 + $months;
	$displayAgeInfo = false;
	$monthFraction = round($days/30, 1);
	$months += $monthFraction;
	if($years || $months){
		$displayAgeInfo = true;
	} else {
		$txt = '0 yr 0 mo';
	}
	if($displayAgeInfo){
		$txt = ($unborn ? '-' : '') . $years .' yr ' . $months . ' mo ';
	}

	$csv .= str_replace(',', '.', $row['first']).' '.str_replace(',', '.', $row['last']).',';
	$csv .= $row['gender'] . ',';
	$csv .= date('m/d/Y', strtotime($row['birth_date'])) . ',';
	$csv .= $txt . ',';
	$csv .= str_replace(',', '.', $row['fname']) . ',';
	$csv .= $row['fstatus'] . ',';
	$csv .= str_replace(',', '.', $row['hmg_worker']) . "\n";
}

echo $csv;
?>

					                         
