<style>
td {page-break-inside:avoid;}
</style>
<script type="text/javascript">
$("document").ready(function(){
	function addPageBreaks(){
		rows = $('.print-row');
		rowsHeight = 0;
		$.each(rows, function(){
			row = $(this);
			rowsHeight += row.height();
			if(rowsHeight > 1065){
				breakHeight = 1110 - rowsHeight;
				row.after('<tr><td colspan="8"><p style="color: red; font-weight: bold; height: ' + breakHeight + 'px;">Add Page Break: ' + (rowsHeight + breakHeight) + 'px</p></td></tr>');
				console.log(row.attr('id'))
				rowsHeight = -84; // minus header height
			}
			//console.log(row.attr('id') + ' Height: ' + row.height())
		});
	};
	//addPageBreaks();
	$(".family").on("click", function(){
		var id = $(this).attr('id').slice(7);
		location.href="index.php?action=family&id=" + id;
	});
	$(".sort").on("click", function(){
		field = ($(this).text().replace(/ /g, '_').toLowerCase());
		if($(this).hasClass('sorting_asc')){
			$(this).removeClass('sorting_asc').addClass('sorting_desc');
			fieldsort = 'desc';
		}
		else if($(this).hasClass('sorting_desc')){
			$(this).removeClass('sorting_desc').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		else {
			$(this).removeClass('sorting').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		if(field == 'parent_name'){
			field = 'first_name_1';
		}
		if(field == 'reason_for_call'){
			field = 'call_reason';
		}
		if(field == 'phone'){
			field = 'primary_phone';
		}
		location.href=window.location+"&field="+field+"&sort="+fieldsort<?= ($search ? '+"&search=' . $search . '"' : '')?>;
	});
	$(document).on('click', '#print-list', function(e){
		e.preventDefault();
		postString = $('#filter-form').serialize();
		window.open('index.php?print=true&' + postString, '');
	});
});
</script>
<? if(is_array($families)) : ?>
<!-- <div class="pageTitleBar">
	<h1>Families Search</h1>
</div> -->
<?
$filteredByLabel = '';
$filteredBy = '';
if(count($filters)){
	$filteredByLabel = '<b style="color: #464646">Active Filters: </b>';
}
foreach($filters as $filter => $value){
	if ($filter == 'hmg_worker') {
		$filter = 'HMG Worker';
	}
	// if value is numeric then we need to look up it's name in the settings table
	if (is_numeric($value)
		&& $filter != 'zip'
		&& $filter != 'school_district'
		&& $filter != 'child_id'
		&& $filter != 'age_max'
		&& $filter != 'age_min'
	) {
		$value = $setting->getValue($value);
	}
	if(is_array($value) && $filter == 'providers'){
		$tmpValues = [];
		foreach ($value as $providerId) {
			$tmpValues[] = $providers->getProviderNameById($providerId);
		}
		$value = $tmpValues;
	}
	if ($value){
		if (is_array($value)) {
			$value = implode($value, ', ');
		}
		$filteredBy .=
			($filteredBy ? ' &mdash; ' : '') .
			ucwords(str_replace('_', ' ', str_replace('_id', ' ', $filter))) .
			': ' .
			$value;
	}
}
?>
	<?= $headerHtml ?>
	<div class="filters" style="padding-bottom: 3px;"><?= $filteredByLabel . $filteredBy ?></div>
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="grid">
	<thead>
		<tr>
			<th class="sort sorting<?=(isset($sorts['first_name_1']) && $sorts['first_name_1'] ? '_' . strtolower($sorts['first_name_1']) : '')?>">Parent Name</th>
			<th class="sort sorting<?=(isset($sorts['language']) && $sorts['language'] ? '_' . strtolower($sorts['language']) : '')?>">Language</th>
			<th class="sort sorting<?=(isset($sorts['city']) && $sorts['city'] ? '_' . strtolower($sorts['city']) : '')?>">City</th>
			<th class="sort sorting<?=(isset($sorts['primary_phone']) && $sorts['primary_phone'] ? '_' . strtolower($sorts['primary_phone']) : '')?>">Phone</th>
			<th class="sort sorting<?=(isset($sorts['email']) && $sorts['email'] ? '_' . strtolower($sorts['email']) : '')?>">Email</th>
			<th class="sort sorting<?=(isset($sorts['best_time']) && $sorts['best_time'] ? '_' . strtolower($sorts['best_time']) : '')?>">Best Time</th>
			<th class="sort sorting<?=(isset($sorts['contact_type']) && $sorts['contact_type'] ? '_' . strtolower($sorts['contact_type']) : '')?>">Contact Type</th>
			<th class="sort sorting<?=(isset($sorts['hmg_worker']) && $sorts['hmg_worker'] ? '_' . strtolower($sorts['hmg_worker']) : '')?>">HMG Worker</th>
		</tr>
	</thead>
	<tbody>
	<? $row = 'odd'; $count = 0; ?>
	<? foreach($families as $family) : ?>
		<tr id="family_<?=$family['id']?>" class="family <?=$row?> print-row">
			<td><?=$family['first_name_1'] . ' ' . $family['last_name_1']?></td>
			<td><?=ucwords(strtolower($family['language']))?></td>
			<td><?=$family['city']?></td>
			<td style="white-space: nowrap;"><?=$family['primary_phone']?></td>
			<td><?=($family['email'])?></td>
			<td><?=($family['best_times'])?></td>
			<td>
			<?
				$contact = '';
				$contact .= ($family['contact_phone'] ? 'Phone' : '');
				$contact .= ($contact ? ', ' : '') . ($family['contact_text'] ? 'Text' : '');
				$contact .= ($contact ? ', ' : '') . ($family['contact_email'] ? 'Email' : '');
				echo $contact;
			?>
			</td>
			<td><?=$family['hmg_worker']?></td>
		</tr>

		<? if($row=='odd'){ $row = 'even'; } else { $row='odd'; } ?>

	<? endforeach; ?>
	</tbody>
</table>
<div class="gridFooter">
	<div style="float: left;" id="gridPaginationText">
		Showing <?= $firstRecord ?>-<?= $lastRecord ?> of  <?= $totalFamilies ?> families
	</div>
</div>
<? else : ?>
<p><br /><em>No result found.</em></p>
<? endif; ?>