
<script type="text/javascript">
$("document").ready(function(){

	$('.fancybox').fancybox({
		padding : '0px', scrolling : 'no',
	});

	$( ".date" ).datepicker();

	$(".family").on("click", function(){
		var idPieces = $(this).attr('id').split('_');
		var id = idPieces[1];
		var pos = idPieces[2];
		location.href="index.php?action=family&id=" + id + "&pos=" + pos;
	});
	$(".sort").on("click", function(){
		field = ($(this).text().replace(/ /g, '_').toLowerCase());
		if($(this).hasClass('sorting_asc')){
			$(this).removeClass('sorting_asc').addClass('sorting_desc');
			fieldsort = 'desc';
		}
		else if($(this).hasClass('sorting_desc')){
			$(this).removeClass('sorting_desc').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		else {
			$(this).removeClass('sorting').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		if(field == 'reason_for_call'){
			field = 'call_reason';
		}
		if(field == 'phone'){
			field = 'primary_phone';
		}
		location.href="index.php?action=families&field="+field+"&sort="+fieldsort<?= ($search ? '+"&search=' . $search . '"' : '')?>;
	});
	$(document).on('click', '#print-list', function(e){
		e.preventDefault();
		curLocation = window.location.href;
		postString = curLocation + '&print=true';
		window.open(postString, '');
	});
	$(document).on('click', '#export-list', function(e){
		e.preventDefault();
		curLocation = window.location.href;
		postString = curLocation + '&export=true';
		window.open(postString, '');
	});
	
	$(document).on('click', '#submitSearchFieldForm', function(e){
		e.preventDefault();
		$('#hidden_quick').val($.trim($('#search').val()));
		$('#filter-form').submit();
		return false;
	});
	
});

</script>

<div class="pageTitleBar">
	<h1>Families</h1>
	<div style="float: right; padding: 0px 4px 4px 0; margin-left: 30px;">
		<form action="index.php"><input type="hidden" name="action" value="family" /><input type="hidden" name="id" value="new" /><input type="submit" name="edit" value="Add Family" class="btn-small" />
		</form>
	</div>

	<div style="float: right;">
	<a href="#advanced-search" class="fancybox" style="font-size: 10px !important; line-height: 10px; font-weight: bold; display: inline-block; padding-top: 7px; text-align: center;">Advanced<br /> Search</a>
	</div>

	<form id="searchFieldForm" action="index.php">
	<input type="hidden" name="action" value="families" />
	<input type="text" id="search" name="filters[quick]" value="<?=isset($_SESSION['families']['filters']['quick']) ? $_SESSION['families']['filters']['quick'] : ''?>" style="float: left; margin-right: 4px;  height: 20px; width: 207px; padding: 0 2px;" />
	<input type="submit" value="Search" class="btn-small" id="submitSearchFieldForm" />
	</form>
</div>

<?=($message ? '<div class="message' . (isset($saved) && $saved ? ' saved' : ' error') . '">' . $message . '</div>' : '')?>

<?
$filteredByLabel = '';
$filteredBy = '';
if(count($filters)){
	$filteredByLabel = '<b style="color: #464646">Active Filters: </b>';
}
foreach($filters as $filter => $value){
	if($filter == 'hmg_worker'){
		$filter = 'HMG Worker';
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(
		is_numeric($value)
		&& $filter != 'zip'
		&& $filter != 'school_district'
		&& $filter != 'child_id'
		&& $filter != 'age_max'
		&& $filter != 'age_min'
	){
		$value = $setting->getValue($value);
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter == 'school_district'){
		$value = $schoolDistrict->getSchoolDistrictById($value);
	}
	if(is_array($value) && $filter == 'providers'){
		$tmpValues = [];
		foreach ($value as $providerId) {
			$tmpValues[] = $providers->getProviderNameById($providerId);
		}
		$value = $tmpValues;
	}
	if(!empty($value)) {
		if(is_array($value)){
			$value = implode($value, ', ');
		}
		$filteredBy .=
			($filteredBy ? ' &mdash; ' : '') .
			ucwords(str_replace('_', ' ', str_replace('_id', ' ', $filter))) .
			': ' .
			$value;
	}
}
echo $filteredByLabel . $filteredBy;
?>

<div class="dataTable" style="height: auto;">
	<div class="titleBar">
		<form id="filter-form" action="index.php" style="padding: 4px 3px 0 4px;"><input type="hidden" name="action" value="families">
			<div style="float: right;">
			<input type="submit" class="btn-small" id="export-list" name="export_list" value="Export" />
			<input type="submit" class="btn-small" id="print-list" name="export_list" value="Print" />
			</div>
			<?= $family->displayHmgWorkerSelect('filters[hmg_worker]', $filters['hmg_worker'], 'all') ?>
			<?= $language->displaySelect('filters[language_id]', $filters['language_id'], 'Language') ?>
			<?= $status->displaySelect('filters[status]', $filters['status'], 'Status', '', false, ' counts-status', false, true) ?>
			<input type="text" class="date" id="start-date" name="filters[start_date]" value="<?= $filters['start_date'] ?>" placeholder="Start Date" />
			<input type="text" class="date" id="end-date" name="filters[end_date]" value="<?= $filters['end_date'] ?>" placeholder = "End Date" />
			<input type="submit" value="Filter" class="btn-small" />  <input type="submit" name="clearFilters" value="Clear" class="btn-small" />
			<input type="hidden" id="hidden_quick" name="filters[quick]" value="<?= isset($filters['quick']) ? $filters['quick'] : ''  ?>" />
		</form>
	</div>
<?php //echo "<pre>";print_r($sorts);die; ?>
<? if(is_array($families)) : ?>
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="grid">
	<thead>
		<tr>
			<th class="sort sorting<?=(isset($sorts['primary_contact']) && $sorts['primary_contact'] ? '_' . strtolower($sorts['primary_contact']) : '')?>">Primary Contact</th>
			<th class="sort sorting<?=(isset($sorts['language']) && $sorts['language'] ? '_' . strtolower($sorts['language']) : '')?>">Language</th>
			<th class="sort sorting<?=(isset($sorts['call_reason']) && $sorts['call_reason'] ? '_' . strtolower($sorts['call_reason']) : '')?>">Reason for call</th>
			<th class="sort sorting<?=(isset($sorts['city']) && $sorts['city'] ? '_' . strtolower($sorts['city']) : '')?>">City</th>
			<th class="sort sorting<?=(isset($sorts['primary_phone']) && $sorts['primary_phone'] ? '_' . strtolower($sorts['primary_phone']) : '')?>">Phone</th>
			<th class="sort sorting<?=(isset($sorts['email']) && $sorts['email'] ? '_' . strtolower($sorts['email']) : '')?>">Email</th>
			<th class="sort sorting<?=(isset($sorts['hmg_worker']) && $sorts['hmg_worker'] ? '_' . strtolower($sorts['hmg_worker']) : '')?>">HMG Worker</th>
		</tr>
	</thead>
	<tbody>
	<?
		$row = 'odd';
		if($pageNumber >= 1){
			$pos = ($pageNumber - 1) * 50;
		} else {
			$pos = 0;
		}
	?>
	<? $familyObj = $family ?>
	<? foreach($families as $family) : ?>

		<tr id="family_<?=$family['id']?>_<?=$pos?>" class="family <?=$row?>">
			<td><?=$family['first_name_1'] . ' ' . $family['last_name_1']?></td>
			<td><?=ucwords(strtolower($family['language']))?></td>
			<td><?=$family['call_reason']?></td>
			<td><?=$family['city']?></td>
			<td><?=$family['primary_phone']?></td>
			<td><?=($family['email'] ? '<a href="mailto:' . $family['email'] . '" title="' . $family['email'] . '">Email</a>' : '')?></td>
			<td><?=$family['hmg_worker']?></td>
		</tr>

		<? if($row=='odd'){ $row = 'even'; } else { $row='odd'; }?>
		<? $pos++; ?>
	<? endforeach; ?>
	</tbody>
</table>
<div class="gridFooter">
	<div style="float: left;" id="gridPaginationText">
		Showing <?= $firstRecord ?>-<?= $lastRecord ?> of  <?= $totalFamilies ?> families
	</div>
	<div style="float: right;" id="gridPages">
		<a href="index.php?action=families<?= ($field ? '&field=' . $field . ($sort ? '&sort=' . $sort : '') : '') ?><?= ($search ? '&search=' . $search : '')?>">First</a>
		<?= ($pageNumber > 1 ? '<a href="index.php?action=families' . ($field ? '&field=' . $field . ($sort ? '&sort=' . $sort : '') : '')  . ($search ? '&search=' . $search : '') . '&page= ' . ($pageNumber - 1) . '">&lt; Prev</a>' : '')?>
		Page <?= $pageNumber ?> of <?= $numPages ?>
		<?= ($pageNumber < $numPages ? '<a href="index.php?action=families' . ($field ? '&field=' . $field . ($sort ? '&sort=' . $sort : '') : '') . '&page= ' . ($pageNumber + 1) . ($search ? '&search=' . $search : '') . '">Next &gt;</a>' : '')?>
		<a href="index.php?action=families<?= ($field ? '&field=' . $field . ($sort ? '&sort=' . $sort : '') : '') ?><?= ($search ? '&search=' . $search : '')?>&page=<?= $numPages ?>">Last</a>
	</div>
</div>
<? else : ?>
<p><br /><em>No result found.</em></p>
<? endif; ?>
<? include_once('advanced-search.phtml');
