<html>
<head>
	<link rel="stylesheet" type="text/css" href="/css/style.css" media="all" />
	<link rel="stylesheet" type="text/css" href="/css/print.css" media="print" />
	<link rel="stylesheet" type="text/css" href="/css/font.css" media="all" />
	<link rel="stylesheet" type="text/css" href="/css/style_subs.css" />
	<link rel="stylesheet" type="text/css" href="/css/hmg.css" />
	<style>
	body {
		margin: 0;
	}
	input.btn-small {
		border: 2px outset #998997 !important;
		border-radius: 7px;
		background: #ccc !important;
		color: #555 !important;
		font: bold 12px/12px arial, helvetica, san-serif !important;
		padding: 3px 6px;
		cursor: pointer;
	}
	.choose-file-input {
		background: #fff;
		font: 9px 'Century Gothic', Arial, Helvetica, Sans Serif !important; 
		width: 138px; 
		margin-left: 0; 
		border: 1px solid #ccc;
	}

	.choose-file-input::-ms-browse {
		width: 40px;
	}

	.attachment-upload {
		display: inline-block;
		font-size: 11px/11px !important;
		padding: 1px 6px !important;
	}
	</style>
</head>
<body>
<form enctype="multipart/form-data" action="/index.php" class="attachment-form" method="post">
	<input type="hidden" name="action" value="screenings-file" />
	<input type="hidden" name="id" value="<?=(is_numeric($_REQUEST['id']) ? $_REQUEST['id'] : $id)?>" />
	<input type="hidden" name="type" value="<?=(isset($_REQUEST['type']) ? $_REQUEST['type'] : $type)?>" />
    <input name="file" type="file" class="choose-file-input" />
    <?if(isset($_REQUEST['show-button'])) : ?>
    	<input type="hidden" name="show-button" value="1" />
    	<input type="submit" class="btn-small attachment-upload" value="Upload" />
	<? endif ?>
</form>
</body>
</html>
<?php
if (is_numeric($_REQUEST['id'])) {
?>
<script type="text/javascript">
	window.onload = function() {
		window.parent.reloadAttachments(<?=$_REQUEST['id']?>);
	}
</script>
<?php
}
?>