<script type="text/javascript">
$("document").ready(function(){

	$('.fancybox').fancybox({
		padding : '0px', scrolling : 'no'
	});

	$( ".date" ).datepicker();

	$(".followUp").on("click", function(){
		var idPieces = $(this).attr('id').split('_');
		var type = idPieces[0];
		var family_id = idPieces[1];
		var child_id = idPieces[2];
		if(type=="childFollowUp"){
			location.href="index.php?action=child&id=" + family_id + "&child_id=" + child_id;
		} else {
			location.href="index.php?action=family&id=" + family_id;
		}
	});
	$(".sort").on("click", function(){
		field = ($(this).text().replace(/ /g, '_').toLowerCase());
		if($(this).hasClass('sorting_asc')){
			$(this).removeClass('sorting_asc').addClass('sorting_desc');
			fieldsort = 'desc';
		}
		else if($(this).hasClass('sorting_desc')){
			$(this).removeClass('sorting_desc').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		else {
			$(this).removeClass('sorting').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		if(field == 'best_time'){
			field = 'best_times';
		}
		if(field == 'days'){
			field = 'best_times_days';
		}
		if(field == 'start_time'){
			field = 'best_times_start';
		}
		if(field == 'end_time'){
			field = 'best_times_end';
		}
		if(field == 'referral'){
			field = 'referred_to';
		}
		
		if(field == 'contact'){
			field = 'contact';
		}
		if(field == 'follow-up_task'){
			field = 'follow_up_task';
		}
		if(field == 'follow-up_date'){
			field = 'follow_up_date';
		}
		location.href="index.php?action=follow-ups&field="+field+"&sort="+fieldsort<?= (isset($search) ? '+"&search=' . $search . '"' : '')?>;
	});
	$(document).on('click', '#print-list', function(e){
		e.preventDefault();
		curLocation = window.location.href;
		postString = curLocation + '&print=true';
		window.open(postString, '');
	});
	$(document).on('click', '#export-list', function(e)
	{
		e.preventDefault();
		postString = $('#filter-form').serialize();
		window.open('index.php?export=true&' + postString, '');
	});
	
});
</script>

<div class="pageTitleBar">
	<h1>Follow-up</h1>
	<div style="float: right; padding: 0px 4px 4px 0; margin-left: 30px;">
		<form action="index.php"><input type="hidden" name="action" value="family" /><input type="hidden" name="id" value="new" /><input type="submit" name="edit" value="Add Family" class="btn-small" /></form>
	</div>

	<div style="float: right;">
	<a href="#advanced-search" class="fancybox" style="font-size: 10px !important; line-height: 10px; font-weight: bold; display: inline-block; padding-top: 7px; text-align: center;">Advanced<br /> Search</a>
	</div>

	<form id="searchFieldForm" action="index.php">
	<input type="hidden" name="action" value="families" />
	<input type="text" id="search" name="filters[quick]" value="<?=isset($_SESSION['families']['filters']['quick']) ? $_SESSION['families']['filters']['quick'] : ''?>" style="float: left; margin-right: 4px;  height: 20px; width: 207px; padding: 0 2px;" />
	<input type="submit" value="Search" class="btn-small" />
	</form>
</div>

<?=($message ? '<div class="message' . (isset($saved) && $saved ? ' saved' : ' error') . '">' . $message . '</div>' : '')?>

<?
$filteredByLabel = '';
$filteredBy = '';
if(count($filters)){
	$filteredByLabel = '<b style="color: #464646">Active Filters: </b>';
}
foreach($filters as $filter => $value){
	if($filter == 'done'){ continue; }
	if($filter == 'hmg_worker'){
		$filter = 'HMG Worker';
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value)){
		$value = $setting->getValue($value);
	}
	if($value){
		if(is_array($value)){
			$value = implode($value, ', ');
		}
		$filteredBy .=
			($filteredBy ? ' &mdash; ' : '') .
			ucwords(str_replace('_', ' ', str_replace('_id', ' ', $filter))) .
			': ' .
			$value;
	}
}
echo $filteredByLabel . $filteredBy;
echo ' &mdash; ' . ($filters['done'] == 'All' ? 'Either' : ($filters['done'] == '1' ? 'Done' : 'Not Done' ));
?>

<div class="dataTable" style="height: auto;">
	<div class="titleBar">
		<form id="filter-form" action="index.php" style="padding: 4px 3px 0 4px;"><input type="hidden" name="action" value="follow-ups">
			<div style="float: right;">
			<input type="submit" class="btn-small" id="print-list" name="export_list" value="Print" />
			</div>
			<?= $family->displayHmgWorkerSelect('filters[hmg_worker]', $filters['hmg_worker'], 'HMG Worker') ?>
			<?= $language->displaySelect('filters[language_id]', $filters['language_id'], 'Language') ?>
			<?= $status->displaySelect('filters[status]', $filters['status'], 'Status', false, null, false, false, true) ?>
			<?= $followUpTask->displaySelect('filters[follow_up_task]', $filters['follow_up_task'], 'Follow Up Task') ?>
			<input type="text" class="date" id="start-date" name="filters[start_date]" value="<?= $filters['start_date'] ?>" placeholder="Start Date" />
			<input type="text" class="date" id="end-date" name="filters[end_date]" value="<?= $filters['end_date'] ?>" placeholder = "End Date" />
			<select name="filters[done]" placeholder="Status">
				<option value="0"<?=($filters['done'] === '0' ? ' selected' : '')?>>Not Done</option>
				<option value="1"<?=($filters['done'] === '1' ? ' selected' : '')?>>Done</option>
				<option value="All"<?=($filters['done'] === 'All' ? ' selected' : '')?>>Either</option>
			</select>
			<input type="submit" value="Filter" class="btn-small" />  <input type="submit" name="clearFilters" value="Clear" class="btn-small" />
		</form>
	</div>

<? 
//echo "<pre>";print_r($followUps);	
if(is_array($followUps)) : ?>
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="grid">
	<thead>
		<tr>
			<th class="sort sorting<?=(isset($sorts['parent_name']) && $sorts['parent_name'] ? '_' . strtolower($sorts['parent_name']) : '')?>">Parent Name</th>
			<th class="sort sorting<?=(isset($sorts['child_name']) && $sorts['child_name'] ? '_' . strtolower($sorts['child_name']) : '')?>">Child Name</th>
			<th class="sort sorting<?=(isset($sorts['language']) && $sorts['language'] ? '_' . strtolower($sorts['language']) : '')?>">Language</th>
			<th class="sort sorting<?=(isset($sorts['best_times_days']) && $sorts['best_times_days'] ? '_' . strtolower($sorts['best_times_days']) : '')?>">Days</th>
			<th class="sort sorting<?=(isset($sorts['best_times_start']) && $sorts['best_times_start'] ? '_' . strtolower($sorts['best_times_start']) : '')?>">Start Time</th>
			<th class="sort sorting<?=(isset($sorts['best_times_end']) && $sorts['best_times_end'] ? '_' . strtolower($sorts['best_times_end']) : '')?>">End Time</th>
			<th class="sort sorting<?=(isset($sorts['contact']) && $sorts['contact'] ? '_' . strtolower($sorts['contact']) : '')?>">Contact</th>
			<th class="sort sorting<?=(isset($sorts['referred_to']) && $sorts['referred_to'] ? '_' . strtolower($sorts['referred_to']) : '')?>">Referral</th>
			<th class="sort sorting<?=(isset($sorts['service']) && $sorts['service'] ? '_' . strtolower($sorts['service']) : '')?>">Service</th>
			<th class="sort sorting<?=(isset($sorts['follow_up_task']) && $sorts['follow_up_task'] ? '_' . strtolower($sorts['follow_up_task']) : '')?>">Follow-up Task</th>
			<th class="sort sorting<?=(isset($sorts['follow_up_date']) && $sorts['follow_up_date'] ? '_' . strtolower($sorts['follow_up_date']) : '')?>">Follow-up Date</th>
			
			<th style="padding-right: 0px;">Done</th>
		</tr>
	</thead>
	<tbody>
	<?	$row = 'odd'; ?>
	<? foreach($followUps as $followUp) :
    
	?>

		<tr id="<?=$followUp['type']?>FollowUp_<?=$followUp['family_id']?>_<?=$followUp['child_id']?>" class="followUp <?=$row?>">
			<td><?=$followUp['parent_name']?></td>
			<td><?=ucwords(strtolower($followUp['child_name']))?></td>
			<td><?=$followUp['language']?></td>
			<td class="best-times-days"><?=ucwords($followUp['best_times_days'])?></td>
			<td class="best-times-start"><?=$followUp['best_times_start']?></td>
			<td class="best-times-end"><?=$followUp['best_times_end']?></td>
			<td>
			<?
				$contact = array();
				if($followUp['contact_phone']){
					$contact[] = 'Phone';
				}
				if($followUp['contact_text']){
					$contact[] = 'Text';
				}
				if($followUp['contact_email']){
					$contact[] = 'Email';
				}
				echo implode(', ', $contact);
			?>
			</td>
			<td><?
				if( $followUp['referred_to_type']  == 'info'){
				  echo $setting->getValue($followUp['referred_to_id']);							    
				}else{
			$siteSeprate = '';
			if($followUp['site_name']){
			$siteSeprate = ': '.$followUp['site_name'];
			}
			echo $followUp['organization_name'].$siteSeprate;
			}
			//=$followUp['referred_to']?></td>
			<td><?php 
				$service = '';
                $services = explode(',',$followUp['service_id']);
                foreach( $services as $ser){
                    $service .= $setting->getValue($ser).',';
                }
                echo substr($service,0,-1);
			 ?></td>
			<td><?=$followUp['follow_up_task'] ?></td>
			<td><?=$followUp['follow_up_date_formatted'] ?></td>
			
			<td><input type="checkbox" disabled <?=($followUp['done'] ? ' checked' : '')?> />
			
			 
			</td>
		</tr>

		<? if($row=='odd'){ $row = 'even'; } else { $row='odd'; }?>

	<? endforeach; ?>
	</tbody>
</table>
<div class="gridFooter">
	<div style="float: left;" id="gridPaginationText">
		Showing <?= $firstRecord ?>-<?= $lastRecord ?> of  <?= $totalFollowUps ?> follow-ups
	</div>
	<div style="float: right;" id="gridPages">
		<a href="index.php?action=follow-ups">First</a>
		<?= ($pageNumber > 1 ? '<a href="index.php?action=follow-ups' . (isset($_REQUEST['field']) ? '&field=' . $_REQUEST['field'] . (isset($_REQUEST['sort']) ? '&sort=' . $_REQUEST['sort'] : '') : '') . '&page= ' . ($pageNumber - 1) . '">&lt; Prev</a>' : '')?>
		Page <?= $pageNumber ?> of <?= $numPages ?>
		<?= ($pageNumber < $numPages ? '<a href="index.php?action=follow-ups' . (isset($_REQUEST['field']) ? '&field=' . $_REQUEST['field'] . (isset($_REQUEST['sort']) ? '&sort=' . $_REQUEST['sort'] : '') : '') . '&page= ' . ($pageNumber + 1) . '">Next &gt;</a>' : '')?>
		<a href="index.php?action=follow-ups<?= (isset($_REQUEST['field']) ? '&field=' . $_REQUEST['field'] . (isset($_REQUEST['sort']) ? '&sort=' . $_REQUEST['sort'] : '') : '') ?>&page=<?= $numPages ?>">Last</a>
	</div>
</div>
<? else : ?>
<p><br /><em>No result found.</em></p>
<? endif; ?>


<? include_once(VIEW_PATH . '/advanced-search.phtml');
