<script type="text/javascript">
$("document").ready(function(){

	$('.fancybox').fancybox({
		padding : '0px', scrolling : 'no'
	});

	$( ".date" ).datepicker();

	$(".followUp").on("click", function(){
		var idPieces = $(this).attr('id').split('_');
		var type = idPieces[0];
		var family_id = idPieces[1];
		var child_id = idPieces[2];
		if(type=="contactFollowUp"){
			location.href="index.php?action=contact&contact_id=" + child_id;
		} else {
			location.href="index.php?action=organization&id=" + family_id;
		}
	});
	$(".sort").on("click", function(){
		field = ($(this).text().replace(/ /g, '_').toLowerCase());
		
		if($(this).hasClass('sorting_asc')){
			$(this).removeClass('sorting_asc').addClass('sorting_desc');
			fieldsort = 'desc';
		}
		else if($(this).hasClass('sorting_desc')){
			$(this).removeClass('sorting_desc').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		else {
			$(this).removeClass('sorting').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		if(field == 'organization_name')
		{
			field == 'organization_name';
			
		}
		
		if(field == 'referred_to')
		{
			field = 'referred_to';
		}
		
		if(field == 'contact')
		{
			field == 'contact';
			
		}
		if(field == 'provider_name'){
			field = 'contact_name';
		}
		
		if(field == 'follow-up_task')
		{
			field = 'follow_up_task';
		}
		if(field == 'follow_up_date')
		{
			field = 'follow_up_date';
		}
		
		
		location.href="index.php?action=organization-follow-ups&field="+field+"&sort="+fieldsort<?= (isset($search) ? '+"&search=' . $search . '"' : '')?>;
	});
	$(document).on('click', '#print-list', function(e){
		e.preventDefault();
		curLocation = window.location.href;
		postString = curLocation + '&print=true';
		window.open(postString, '');
	});
	$(document).on('click', '#export-list', function(e){
		e.preventDefault();
		postString = $('#filter-form').serialize();
		window.open('index.php?export=true&' + postString, '');
	});
});
</script>

<div class="pageTitleBar">
	<h1>Organization Follow-up</h1>
	<div style="float: right; padding: 0px 4px 4px 0; margin-left: 30px;">
		<form action="index.php"><input type="hidden" name="action" value="organization" /><input type="hidden" name="id" value="new" /><input type="submit" name="edit" value="Add Organization" class="btn-small" /></form>
	</div>

	<div style="float: right;">
	<a href="#advanced-search" class="fancybox" style="font-size: 10px !important; line-height: 10px; font-weight: bold; display: inline-block; padding-top: 7px; text-align: center;">Advanced<br /> Search</a>
	</div>

	<form id="searchFieldForm" action="index.php">
	<input type="hidden" name="action" value="<?php  if(isset($_REQUEST['action'])) echo  $_REQUEST['action']; else "organizations";?>" />
	<input type="text" id="search" name="filters[quick]" value="<?=isset($_SESSION['organizations']['filters']['quick']) ? $_SESSION['organizations']['filters']['quick'] : ''?>" style="float: left; margin-right: 4px;  height: 20px; width: 207px; padding: 0 2px;" />
	<input type="submit" value="Search" class="btn-small" />
	</form>
</div>

<?=($message ? '<div class="message' . (isset($saved) && $saved ? ' saved' : ' error') . '">' . $message . '</div>' : '')?>

<?
$filteredByLabel = '';
$filteredBy = '';
if(count($filters)){
	$filteredByLabel = '<b style="color: #464646">Active Filters: </b>';
}
foreach($filters as $filter => $value){
	if($filter == 'done'){ continue; }
	if($filter == 'hmg_worker'){
		$filter = 'HMG Worker';
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value)){
		$value = $setting->getValue($value);
	}
	if($value){
		if(is_array($value)){
			$value = implode($value, ', ');
		}
		$filteredBy .=
			($filteredBy ? ' &mdash; ' : '') .
			ucwords(str_replace('_', ' ', str_replace('_id', ' ', $filter))) .
			': ' .
			$value;
	}
}
echo $filteredByLabel . $filteredBy;
echo ' &mdash; ' . ($filters['done'] == 'All' ? 'Either' : ($filters['done'] == '1' ? 'Done' : 'Not Done' ));

?>

<div class="dataTable" style="height: auto;">
	<div class="titleBar">
		<form id="filter-form" action="index.php" style="padding: 4px 3px 0 4px;"><input type="hidden" name="action" value="<?php  if(isset($_REQUEST['action'])) echo  $_REQUEST['action']; else "organizations";?>">
			<div style="float: right;">
			<input type="submit" class="btn-small" id="print-list" name="export_list" value="Print" />
			</div>
			<?php /*<?=  $organization_name->displaySelect('filters[referred_to]', isset($filters['oragnization_name_id']) ? $filters['oragnization_name_id'] : ''); ?>*/ ?>
			<?=  $organization->displayHmgWorkerSelect('filters[hmg_worker]', $filters['hmg_worker'], 'HMG Worker')?>
			
			<?= $followUpTask->displaySelect('filters[follow_up_task_id]', $filters['follow_up_task_id'], 'Follow Up Task') ?>
			<input type="text" class="date" id="start-date" name="filters[start_date]" value="<?= $filters['start_date'] ?>" placeholder="Start Date" />
			<input type="text" class="date" id="end-date" name="filters[end_date]" value="<?= $filters['end_date'] ?>" placeholder = "End Date" />
			<select name="filters[done]" placeholder="Status">
				<option value="0"<?=($filters['done'] === '0' ? ' selected' : '')?>>Not Done</option>
				<option value="1"<?=($filters['done'] === '1' ? ' selected' : '')?>>Done</option>
				<option value="All"<?=($filters['done'] === 'All' ? ' selected' : '')?>>Either</option>
			</select>
			<input type="submit" value="Filter" class="btn-small" />  <input type="submit" name="clearFilters" value="Clear" class="btn-small" />
		</form>
	</div>

<? if(is_array($OrganizationFollowUpss)) : 

?>
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="grid">
	<thead>
		<tr>
			<th class="sort sorting<?=(isset($sorts['organization']) && $sorts['organization'] ? '_' . strtolower($sorts['organization']) : '')?>">Organization</th>
			<th class="sort sorting<?=(isset($sorts['site']) && $sorts['site'] ? '_' . strtolower($sorts['site']) : '')?>">Site</th>
			<th class="sort sorting<?=(isset($sorts['contact_name']) && $sorts['contact_name'] ? '_' . strtolower($sorts['contact_name']) : '')?>">Provider Name</th>
			<th class="sort sorting<?=(isset($sorts['referred_to']) && $sorts['referred_to'] ? '_' . strtolower($sorts['referred_to']) : '')?>">Referred To</th>
			<!--th class="sort sorting<?=(isset($sorts['contact']) && $sorts['contact'] ? '_' . strtolower($sorts['contact']) : '')?>">contact</th-->
			<th class="sort sorting<?=(isset($sorts['service']) && $sorts['service'] ? '_' . strtolower($sorts['service']) : '')?>">Service</th>
			<th class="sort sorting<?=(isset($sorts['follow_up_task']) && $sorts['follow_up_task'] ? '_' . strtolower($sorts['follow_up_task']) : '')?>">Follow-Up Task</th>
			
			<th class="sort sorting<?=(isset($sorts['follow-up_date']) && $sorts['follow-up_date'] ? '_' . strtolower($sorts['follow-up_date']) : '')?>">Follow-up Date</th>
			
			
			
			<th style="padding-right: 0px;">Done</th>
		</tr>
	</thead>
	<tbody>
	<? $row = 'odd'; 
	?>
	<? foreach($OrganizationFollowUpss as $followUp) : 
	
	   //echo "<pre>";
	   //print_r($followUp);
	   
	   //echo "</pre>";
    
	?>
<?
    if(isset($followUp['type']) && !empty($followUp['type']))
 $id=$followUp['type'].'FollowUp_'.$followUp['organization_sites_id'];
           else 
$id='contactFollowUp_'.$followUp['organization_sites_id'].'_'.$followUp['contact_id'];

?>  
		<tr id="<?= $id ?>" class="followUp <?=$row?>">
			<td><?=$followUp['org_name']?></td>
			<td><?=$followUp['site']?></td>
			<td><?=$followUp['ct_name']?></td>
			<td>
			<?php if( $followUp['referred_to_type']  == 'info'){
				  echo $setting->getValue($followUp['referred_to_id']);							    
				}else{
			if(!empty($followUp['org_name_2']) && !empty($followUp['site_name_2'])){
				echo $followUp['org_name_2'].': '.$followUp['site_name_2'];		
			}else if(!empty($followUp['org_name_2']) && empty($followUp['site_name_2'])){
				echo $followUp['org_name_2'];
			}
			else if(empty($followUp['org_name_2']) && !empty($followUp['site_name_2'])){
				echo $followUp['site_name_2'];
			}
			else{
				
			}
			}
			
	
			?></td>
			<td><?php 
				$service = '';
                $services = explode(',',$followUp['service_id']);
                foreach( $services as $ser){
                    $service .= $setting->getValue($ser).',';
                }
                echo substr($service,0,-1);
			 ?></td>

			<td><?= $followUp['follow_up_task'] ?></td>
				
			<td><? echo ($followUp['follow_up_date_formatted'] != '01/01/1970') 
				? $followUp['follow_up_date_formatted'] : ''; ?></td>
				
			
			<td><input type="checkbox" disabled <?=($followUp['done'] ? ' checked' : '')?> /></td>
		</tr>

		<? if($row=='odd'){ $row = 'even'; } else { $row='odd'; }?>

	<? endforeach; ?>
	</tbody>
</table>
<div class="gridFooter">
	<div style="float: left;" id="gridPaginationText">
		Showing <?= $firstRecord+1  ?>-<?= $lastRecord  ?> of  <?= $totalFollowUps-1 ?> follow-ups
	</div>
	<div style="float: right;" id="gridPages">
		<a href="index.php?action=organization-follow-ups">First</a>
		<?= ($pageNumber > 1 ? '<a href="index.php?action=organization-follow-ups' . (isset($_REQUEST['field']) ? '&field=' . $_REQUEST['field'] . (isset($_REQUEST['sort']) ? '&sort=' . $_REQUEST['sort'] : '') : '') . '&page= ' . ($pageNumber - 1) . '">&lt; Prev</a>' : '')?>
		Page <?= $pageNumber ?> of <?= $numPages ?>
		<?= ($pageNumber < $numPages ? '<a href="index.php?action=organization-follow-ups' . (isset($_REQUEST['field']) ? '&field=' . $_REQUEST['field'] . (isset($_REQUEST['sort']) ? '&sort=' . $_REQUEST['sort'] : '') : '') . '&page= ' . ($pageNumber + 1) . '">Next &gt;</a>' : '')?>
		<a href="index.php?action=organization-follow-ups<?= (isset($_REQUEST['field']) ? '&field=' . $_REQUEST['field'] . (isset($_REQUEST['sort']) ? '&sort=' . $_REQUEST['sort'] : '') : '') ?>&page=<?= $numPages ?>">Last</a>
	</div>
</div>
<? else : ?>
<p><br /><em>No result found.</em></p>
<? endif; ?>


<? include_once(VIEW_PATH . '/organizations-advanced-search.phtml');
