<script type="text/javascript">
$("document").ready(function(){

	$('.fancybox').fancybox({
		padding : '0px', scrolling : 'no'
	});

	$( ".date" ).datepicker();

	$(".followUp").on("click", function(){
		var idPieces = $(this).attr('id').split('_');
		var type = idPieces[0];
		var family_id = idPieces[1];
		var child_id = idPieces[2];
		if(type=="childFollowUp"){
			location.href="index.php?action=child&id=" + family_id + "&child_id=" + child_id;
		} else {
			location.href="index.php?action=organization&id=" + family_id;
		}
	});
	$(".sort").on("click", function(){
		field = ($(this).text().replace(/ /g, '_').toLowerCase());
		
		
		
		if($(this).hasClass('sorting_asc')){
			$(this).removeClass('sorting_asc').addClass('sorting_desc');
			fieldsort = 'desc';
		}
		else if($(this).hasClass('sorting_desc')){
			$(this).removeClass('sorting_desc').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		else {
			$(this).removeClass('sorting').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		if(field == 'oragnization_name')
		{
			field == 'oragnization_name';
			
		}
		
		if(field == 'referred_to')
		{
			field = 'referred_to';
		}
		
		if(field == 'contact')
		{
			field == 'contact';
			
		}
		if(field == 'hmg_worker'){
			field = 'hmg_worker';
		}
		
	
		if(field == 'follow_up_date')
		{
			field = 'follow_up_date';
		}
		
		
       
		
		location.href="index.php?action=organization-follow-ups&field="+field+"&sort="+fieldsort<?= (isset($search) ? '+"&search=' . $search . '"' : '')?>;
	});
	$(document).on('click', '#print-list', function(e){
		e.preventDefault();
		curLocation = window.location.href;
		postString = curLocation + '&print=true';
		window.open(postString, '');
	});
	$(document).on('click', '#export-list', function(e){
		e.preventDefault();
		postString = $('#filter-form').serialize();
		window.open('index.php?export=true&' + postString, '');
	});
});
</script>

<? if(isset($followUps) && is_array($followUps)) : ?>

<? 
$filteredByLabel = '';
$filteredBy = '';
if(count($filters)){
	$filteredByLabel = '<b style="color: #464646">Active Filters: </b>';
}
foreach($filters as $filter => $value){
	if($filter == 'done'){ continue; }
	if($filter == 'hmg_worker'){
		$filter = 'HMG Worker';
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value)){
		$value = $setting->getValue($value);
	}
	if($value){
		if(is_array($value)){
			$value = implode($value, ', ');
		}
		$filteredBy .=
			($filteredBy ? ' &mdash; ' : '') .
			ucwords(str_replace('_', ' ', str_replace('_id', ' ', $filter))) . 
			': ' . 
			$value;
	}
}
$filteredBy .= ' &mdash; ' . ($filters['done'] == 'All' ? 'Either' : ($filters['done'] == '1' ? 'Done' : 'Not Done' ));
?>

<?= $headerHtml ?>
	<div class="filters" style="padding-bottom: 3px;"><?= $filteredByLabel . $filteredBy ?></div>


	<table cellpadding="0" cellspacing="0" border="0" class="display" id="grid">
	<thead>
		<tr>
			<th class="sort sorting<?=(isset($sorts['organization_name']) && $sorts['organization_name'] ? '_' . strtolower($sorts['organization_name']) : '')?>">Organization Name</th>
			<th class="sort sorting<?=(isset($sorts['hmg_worker']) && $sorts['hmg_worker'] ? '_' . strtolower($sorts['hmg_worker']) : '')?>">Hmg worker</th>
			<th class="sort sorting<?=(isset($sorts['referred_to']) && $sorts['referred_to'] ? '_' . strtolower($sorts['referred_to']) : '')?>">Referred To</th>
			<th class="sort sorting<?=(isset($sorts['contact']) && $sorts['contact'] ? '_' . strtolower($sorts['contact']) : '')?>">Provider Name</th>
			
			<th class="sort sorting<?=(isset($sorts['follow_up_date']) && $sorts['follow_up_date'] ? '_' . strtolower($sorts['follow_up_date']) : '')?>">Follow up Date</th>
			
			
			
			<th style="padding-right: 0px;">Done</th>
		</tr>
	</thead>
	<tbody>
	<? $row = 'odd'; ?>
	<? foreach($followUps as $followUp) : 
	  
	?>

		<tr id="<?=$followUp['type']?>FollowUp_<?=$followUp['organization_id']?>" class="followUp <?=$row?>">
			<td><?=$followUp['org_name']?></td>
			<td><?=$followUp['hmg_worker']?></td>
			<td><?php if( $followUp['referred_to_type']  == 'info'){
				  echo $setting->getValue($followUp['referred_to_id']);							    
				}else{ echo $followUp['referred_to']; } ?></td>
			<td><?= $followUp['contact']?></td>
			
			<td><?=$followUp['follow_up_date_formatted']?></td>
			
			<td><input type="checkbox" disabled <?=($followUp['done'] ? ' checked' : '')?> /></td>
		</tr>

		<? if($row=='odd'){ $row = 'even'; } else { $row='odd'; }?>

	<? endforeach; ?>
	</tbody>
</table>
<div class="gridFooter">
	<div style="float: left;" id="gridPaginationText">
		Showing <?= $firstRecord ?>-<?= $lastRecord ?> of  <?= $totalFollowUps ?> follow-ups
	</div>
	<div style="float: right;" id="gridPages">
		
	</div>
</div>
<? else : ?>
<p><br /><em>No result found.</em></p>
<? endif; ?>


