<?
use Hmg\Models\Setting;
?>
<style type="text/css">
.titleBar{ height: auto; min-height: 30px; }
</style>
<script type="text/javascript">
$("document").ready(function(){
	
	$('.fancybox').fancybox({
		padding : '0px', scrolling : 'no',
	});

	$( ".date" ).datepicker();

	$(".organization").on("click", function(){
		var idPieces = $(this).attr('id').split('_');
		var id = idPieces[1];
		var pos = idPieces[2];
		location.href="index.php?action=organization&id=" + id + "&pos=" + pos;
	});
	$(".sort").on("click", function(){
		field = ($(this).text().replace(/ /g, '_').toLowerCase());
		if($(this).hasClass('sorting_asc')){
			$(this).removeClass('sorting_asc').addClass('sorting_desc');
			fieldsort = 'desc';
		}
		else if($(this).hasClass('sorting_desc')){
			$(this).removeClass('sorting_desc').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		else {
			$(this).removeClass('sorting').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		if(field == 'reason_for_call'){
			field = 'call_reason';
		}
		if(field == 'phone'){
			field = 'primary_phone';
		}
		location.href="index.php?action=organizations&field="+field+"&sort="+fieldsort<?= ($search ? '+"&search=' . $search . '"' : '')?>;
	});
	$(document).on('click', '#print-list', function(e){
		e.preventDefault();
		curLocation = window.location.href;
		postString = curLocation + '&print=true';
		window.open(postString, '');
	});
	$(document).on('click', '#export-list', function(e){
		e.preventDefault();
		curLocation = window.location.href;
		postString = curLocation + '&export=true';
		window.open(postString, '');
	});
	
	$(document).on('click', '#submitSearchFieldForm', function(e){
		e.preventDefault();
		$('#hidden_quick').val($.trim($('#search').val()));
		$('#filter-form').submit();
		return false;
	});
	
});

</script>
<script type="text/javascript" src="js/autosuggest.js"></script>
<div class="pageTitleBar">
	<h1>Organizations</h1>
	<div style="float: right; padding: 0px 4px 4px 0; margin-left: 30px;">
		<form action="index.php"><input type="hidden" name="action" value="organization" /><input type="hidden" name="id" value="new" /><input type="submit" name="edit" value="Add Organization" class="btn-small" /></form>
	</div>

	<div style="float: right;">
	<a href="#advanced-search" class="fancybox" style="font-size: 10px !important; line-height: 10px; font-weight: bold; display: inline-block; padding-top: 7px; text-align: center;">Advanced<br /> Search</a>
	</div>

	<form id="searchFieldForm" action="index.php" style="position:relative;">
	<input type="hidden" name="action" value="organizations" />
	<input type="text" id="search" name="filters[quick]" value="<?=isset($_SESSION['organizations']['filters']['quick']) ? $_SESSION['organizations']['filters']['quick'] : ''?>" style="float: left; margin-right: 4px;  height: 20px; width: 207px; padding: 0 2px;" 
								class="autosuggest-input rounded"								
								data-query-string="action=referral-org&search="
								autocomplete="off" />
							<div class="autosuggest-selection-container" style="top: 30px;"></div>
	<input type="submit" value="Search" class="btn-small" id="submitSearchFieldForm" />
	</form>
</div>

<?=($message ? '<div class="message' . (isset($saved) && $saved ? ' saved' : ' error') . '">' . $message . '</div>' : '')?>

<?
$filteredByLabel = '';
$filteredBy = '';
if(count($filters)){
	$filteredByLabel = '<b style="color: #464646">Active Filters: </b>';
}
foreach($filters as $filter => $value){
	if($filter == 'hmg_worker'){
		$filter = 'HMG Worker';
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(
		is_numeric($value)
		&& $filter != 'zip'
		&& $filter != 'school_district'
		&& $filter != 'child_id'
	){
		$value = $setting->getValue($value);
	}
	// if value is numeric then we need to look up it's name in the settings table
	if(is_numeric($value) && $filter == 'school_district'){
		$value = $schoolDistrict->getSchoolDistrictById($value);
	}
	if(is_array($value) && $filter == 'providers'){
		$tmpValues = [];
		foreach ($value as $providerId) {
			$tmpValues[] = $providers->getProviderNameById($providerId);
		}
		$value = $tmpValues;
	}
	if(!empty($value)) {
		if(is_array($value)){
			$value = implode($value, ', ');
		}
		$filteredBy .=
			($filteredBy ? ' &mdash; ' : '') .
			ucwords(str_replace('_', ' ', str_replace('_id', ' ', $filter))) .
			': ' .
			$value;
	}
}
echo $filteredByLabel . $filteredBy;
?>

<div class="dataTable" style="height: auto;">
	<div class="titleBar">
		<form id="filter-form" action="index.php" style="padding: 4px 3px 0 4px;"><input type="hidden" name="action" value="organizations">
			<div style="float: right;">
			<input type="submit" class="btn-small" id="export-list" name="export_list" value="Export" />
			<input type="submit" class="btn-small" id="print-list" name="export_list" value="Print" />
			</div>
			<?//= $organization->displayHmgWorkerSelect('filters[hmg_worker]', $filters['hmg_worker'], 'HMG Worker') ?>
			<?= $regions->displaySelect('filters[region_id]', $filters['region_id'], 'Region');?>
			<?= $type->displaySelect('filters[organization_type_id]', $filters['organization_type_id'], 'Type') ?>
			<?= $status->displaySelect('filters[status]',$filters['status'],'Status') ?>
			<?= $county->displaySelect('filters[county]', $filters['county'], 'County', '', false, '', false, true) ?>
			<?= $partnership->displaySelect('filters[partnership_level_id]', $filters['partnership_level_id'], 'Partnership Level', '', false, '', true, true) ?>
			<input type="text" class="date" id="start-date" name="filters[start_date]" value="<?= $filters['start_date'] ?>" placeholder="Start Date" />
			<input type="text" class="date" id="end-date" name="filters[end_date]" value="<?= $filters['end_date'] ?>" placeholder = "End Date" />
			<input type="submit" value="Filter" class="btn-small" />  <input type="submit" name="clearFilters" value="Clear" class="btn-small" />
			<input type="hidden" id="hidden_quick" name="filters[quick]" value="<?= isset($filters['quick']) ? $filters['quick'] : ''  ?>" />
		</form>
	</div>
<?php //echo "<pre>";print_r($sorts);die; ?>
<? if(is_array($organizations)) : ?>
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="grid">
	<thead>
		<tr>
			<th class="sort sorting<?=(isset($sorts['organization']) && $sorts['organization'] ? '_' . strtolower($sorts['organization']) : '')?>">Organization</th>
			<th class="sort sorting<?=(isset($sorts['site']) && $sorts['site'] ? '_' . strtolower($sorts['site']) : '')?>">Site</th>
			<th class="sort sorting<?=(isset($sorts['organization_type']) && $sorts['organization_type'] ? '_' . strtolower($sorts['organization_type']) : '')?>">Organization Type</th>
			<th class="sort sorting<?=(isset($sorts['city']) && $sorts['city'] ? '_' . strtolower($sorts['city']) : '')?>">City</th>
			<th class="sort sorting<?=(isset($sorts['primary_phone']) && $sorts['primary_phone'] ? '_' . strtolower($sorts['primary_phone']) : '')?>">Phone</th>
			<th class="sort sorting<?=(isset($sorts['partnership_level']) && $sorts['partnership_level'] ? '_' . strtolower($sorts['partnership_level']) : '')?>">Partnership Level</th>
			<th class="sort sorting<?=(isset($sorts['region']) && $sorts['region'] ? '_' . strtolower($sorts['region']) : '')?>">Region</th>
		</tr>
	</thead>
	<tbody>
	<?
		$row = 'odd';
		if($pageNumber >= 1){
			$pos = ($pageNumber - 1) * 50;
		} else {
			$pos = 0;
		}
	?>
	<? $organizationObj = $organization; //echo "<pre>";print_r($organizations);?>
	<? foreach($organizations as $organization) : ?>

		<tr id="organization_<?=$organization['organization_sites_id']?>_<?=$pos?>" class="organization <?=$row?>">
			<td><?=$organization['organization_name']?></td>
			<td><?=isset($organization['site']) ? $organization['site'] : ''?></td>
			<td><?=$organization['organization_type']?></td>
			<td><?=$organization['city']?></td>
			<td><?=$organization['primary_phone']?></td>
			<td><?=($organization['partnership_level'] ? $organization['partnership_level'] : '')?></td>
			<td><?=$organization['region']?></td>
		</tr>

		<? if($row=='odd'){ $row = 'even'; } else { $row='odd'; }?>
		<? $pos++; ?>
	<? endforeach; ?>
	</tbody>
</table>
<div class="gridFooter">
	<div style="float: left;" id="gridPaginationText">
		Showing <?= $firstRecord ?>-<?= $lastRecord ?> of  <?= $totalOrganizations ?> organizations
	</div>
	<div style="float: right;" id="gridPages">
		<a href="index.php?action=organizations<?= ($field ? '&field=' . $field . ($sort ? '&sort=' . $sort : '') : '') ?><?= ($search ? '&search=' . $search : '')?>">First</a>
		<?= ($pageNumber > 1 ? '<a href="index.php?action=organizations' . ($field ? '&field=' . $field . ($sort ? '&sort=' . $sort : '') : '')  . ($search ? '&search=' . $search : '') . '&page= ' . ($pageNumber - 1) . '">&lt; Prev</a>' : '')?>
		Page <?= $pageNumber ?> of <?= $numPages ?>
		<?= ($pageNumber < $numPages ? '<a href="index.php?action=organizations' . ($field ? '&field=' . $field . ($sort ? '&sort=' . $sort : '') : '') . '&page= ' . ($pageNumber + 1) . ($search ? '&search=' . $search : '') . '">Next &gt;</a>' : '')?>
		<a href="index.php?action=organizations<?= ($field ? '&field=' . $field . ($sort ? '&sort=' . $sort : '') : '') ?><?= ($search ? '&search=' . $search : '')?>&page=<?= $numPages ?>">Last</a>
	</div>
</div>
<? else : ?>
<p><br /><em>No result found.</em></p>
<? endif; ?>
<? include_once('organizations-advanced-search.phtml');
