<?php //echo "<pre>";print_r($_SESSION['user']);die;?>
<link href="css/chosen.css" rel="stylesheet">
<script type="text/javascript" src="js/chosen.jquery.js"></script>

<script type="text/javascript">

var newChildCurrentIndex = 0;

$("document").ready(function(){

	$(".chosen-select").chosen();

	$('.fancybox').fancybox({
		padding : '0px', scrolling : 'no'
	});

	$('.date').keyup(function(){
		var value =	$(this).val();
		//console.log(value);
	});
	
	//check whether the user has permission for county/region
	$("input[name=county_id]").bind("change", function() {
		//ajax call check permissions
		var $this = $(this);
		var cid   = $.trim($(this).val());
		var uid   = "<?php echo $_SESSION['user']['id']; ?>";
		var json  = '{ "cid" : "' + cid + '", "uid" : "' + uid + '" }';
		$.ajax({
			type		: "POST",
			data		: { 'action' : 'organization', 'check_permissions' : 'true', 'json' : json },
			url			: 'index.php',
			dataType	: 'json',
			beforeSend	: function() {},
			error		: function() {},
			success		: function( result ) {
				if(result && result.status == false) {
					$this.val('');
					$this.next('.autosuggest-input').val('');
					alert('You do not have permission to save a organization in a County outside of your Region. If you have received this message in error, please contact your Help Me Grow Administrator.');
				}
			}
		});
	});

    $('.infoPane').on('keyup', '.county-lookup', function(event){
    	input = $(this);
		if(input.val().length >= 5){
			searchString = input.val().substring(0, 5);
			$.post('index.php', 'action=zip&zip=' + searchString, function(data){
				county = data.county;
				updateCountySelect(county);
			})
		}
    });
    $('.infoPane').on('change', '[name="city_id"]', function(event){
		input = $('input[name="data[city]"]');
		searchString = input.val();
		$.post('index.php', 'action=zip&city=' + searchString, function(data){
			county = data.county;
			updateCountySelect(county);
			//ajax call check permissions
			var uid   = "<?php echo $_SESSION['user']['id']; ?>";
			var json  = '{ "cid" : "' + data.county + '", "uid" : "' + uid + '" }';
			$.ajax({
				type		: "POST",
				data		: { 'action' : 'organization', 'check_permissions' : 'true', 'json' : json },
				url			: 'index.php',
				dataType	: 'json',
				beforeSend	: function() {},
				error		: function() {},
				success		: function( result ) {
					if(result && result.status == false) {
						$('input[name=county_id]').val('');
						$('input[name=county_id]').next('.autosuggest-input').val('');
						alert('You do not have permission to save a organization in a County outside of your Region. If you have received this message in error, please contact your Help Me Grow Administrator.');
					}
				}
			});
		});
    });
	$(".addAnotherChild").on("click", function(){
		lastChild = $('#childrenDiv .infoTable:last').not('.newChild');
		if(!lastChild.length){
			lastChild = $('#childrenDiv .editChild:last').not('.newChild');
		}
		lastTabIndex = parseInt(lastChild.find('textarea').attr('tabindex'));
		if(isNaN(lastTabIndex)){
			lastTabIndex = 50;
		}
		newChild = $(".newChild");
		cloneChild = newChild.clone();
		cloneChild.removeClass('newChild');
		inputs = cloneChild.find('input, textarea, select').not('.prenatal');
		inputs.each(function(index){
			lastTabIndex++;
			if($(this).hasClass('deleteAnotherChild')) {
				$(this).attr('data-id', newChildCurrentIndex);
				return;
			}
			myname = $(this).attr('name');
			tmpname = myname.replace(/[^0-9]/g, "");
			i = parseInt(tmpname);
			newname = myname.replace("template[0]", "children[NEW" + newChildCurrentIndex + "]");
			$(this).attr('name', newname);
			$(this).attr('tabindex', lastTabIndex);
			if(newname.indexOf('birth_date') != -1){
				$(this).addClass('date');
				$(this).addClass('date birth');
			}
			if(newname.indexOf('birth_due_date') != -1){
				$(this).addClass('date birth-due-date');
				//$(this).addClass('date birth-due-date birth');
			}
		});
		newChildCurrentIndex++;
		cloneChild.appendTo("#childrenDiv");
		setTimeout(function(){
			$('.date').datepicker();
			if($('#childrenDiv .infoTable').not('.newChild').length > 1){
				$('#childrenDiv .infoTable:last').not('.newChild').find('input').eq(1).focus();
			}
		}, 1000);
	});
	<? if($addChild) : ?>
	$(".addAnotherChild").trigger('click');
	<? endif; ?>

	$('.delete-name').on('click', function(e){
		$('.delete-child').attr('name', e.target.name);
		$('.cancel-delete').focus();
		setTimeout(function() {
			$('.cancel-delete').focus();
		}, 500);
	});
	$('.delete-child').on('click', function(e){
		$('#save-trigger').attr('name', e.target.name);
		$('#save-trigger').val('1');
		$('#organizationForm').submit();
	});
	$(document).on('click', '.deleteAnotherChild', function(e){
		$('#new_child_ref').val($(this).attr('data-id'));
		$.fancybox.open('#new-child-delete-div');
		$('.cancel-delete').focus();
		setTimeout(function() {
			$('.cancel-delete').focus();
		}, 500);
	});
	$(document).on('click', '.cancel-delete', function(e){
		$.fancybox.close();
	});
	$(document).on('click', '.new-delete-child', function(e){
		var data_id = $('#new_child_ref').val();
		$('input[data-id="'+data_id+'"]').parentsUntil('.infoTable').remove();
		$.fancybox.close();
	});
	
	$('.delete-organization').on('click', function(e){
		confirmed = confirm('Are you sure you want to delete this organization?');
		if (confirmed) {
			$('#save-trigger').attr('name', 'delete');
			$('#save-trigger').val('1');
			$('#organizationForm').submit();
		}
	});

	$('.save-shortcut').on('click', function(e){

		$('#organizationForm').find('.save-form').click();
		e.preventDefault();
	});

	$('#organizationForm .save-form').on('click', function(e) {

		var return_value = dateValidation(); 
		if(!return_value){
			return false;
		}
		$('.btn-small.save-shortcut, .btn-small.save-form').prop('disabled', true).addClass('disabled');
		$('#save-trigger').val('1');
		$('#organizationForm').submit();
	});

	function placeFocusOnMissing(){
		$('#organizationForm').find('.required').each(function(index){
			if($(this).val() == ''){
				$(this).focus();
				return false;
			}
		});

	}

	function updateCountySelect(county){
		select = $("[name*='county']");
		select.val(county);
	}

	<? if($message) : ?>
	placeFocusOnMissing();
	<? endif; ?>
	// initialize date picker
	$('.date').datepicker();

	function dateValidation(){
		//return true;
		var is_birth_valid= true;
		$('.birth').each(function(){
			if($(this).hasClass('not_count'))
			{
				return ;
			}
			if($(this).val() == "")
			{
				return;
			}
			
		    var Val_date = $(this).val();    
	      	var match1 = /^(\d{1,2})\/(\d{1,2})\/(\d{2})$/.test(Val_date);
	      	var match2 = /^(\d{1,2})\/(\d{1,2})\/(\d{4})$/.test(Val_date);
	      	
	      	if(match1 || match2)
	      	{
	      		try{
		      		var match = Val_date.match(/(\d{1,2})\/(\d{1,2})\/(\d{2,4})/);
			      	var mm = match[1];
				    var dd = match[2];
				    var yy = match[3];
					console.log($.datepicker.parseDate("dd/mm/yy", dd + "/" + mm + "/" + yy));
					$.datepicker.parseDate("dd/mm/yy", dd + "/" + mm + "/" + yy, null);
				}
				catch(error)
				{
					alert("Please enter VALID BIRTH DATE");
					is_birth_valid= false;
					return ;
					return false;
				}
			}
			else{
				alert("Please enter VALID BIRTH DATE");
				is_birth_valid= false;
				return ;
				return false;
			}

		});
		if(is_birth_valid) return true;
	}
});
</script>
<script type="text/javascript" src="js/autosuggest.js"></script>

<div class="infoMain">

	<div class="titleBar">
	<div style="float: right; padding: 4px 4px 4px 0; margin-left: 30px;">
		<?= (isset($data['id']) && is_numeric($data['id']) ? '<form action="index.php" style="display: inline-block;"><input type="hidden" name="action" value="organization"  /><input type="hidden" name="id" value="' .  $data['organization_sites_id'] . '" /><input type="hidden" name="organization_sites_id" value="' .  $data['organization_sites_id'] . '" /><input type="submit" value="View Organization" class="btn-small" /></form>' : '')?> <form action="index.php" style="display: inline-block;"><input type="hidden" name="action" value="organizations" /><input type="hidden" name="field" value="<?=$field?>" /><input type="hidden" name="sort" value="<?=$sort?>" /><input type="submit" value="Organizations List" class="btn-small" /> <input type="submit" value="Save" class="btn-small save-shortcut" /></form>
		<?=(isset($_SESSION['totalOrganization']) && ($pos - 1) > 0 ? '<form action="index.php" style="display: inline-block;"><input type="hidden" name="action" value="organization" /><input type="hidden" name="id" value="' . $data['id'] . '" /><input type="hidden" name="organization_sites_id" value="' .  $data['organization_sites_id'] . '" /><input type="hidden" name="pos" value="' . ($pos + 1) . '" /><input type="submit" name="edit" value=" " class="prev" /></form>' : '')?>
		<?=($data['id'] != null && isset($_SESSION['totalOrganization']) && ($pos - 1) < $_SESSION['totalOrganization'] ? '<form action="index.php" style="display: inline-block;"><input type="hidden" name="action" value="organization" /><input type="hidden" name="id" value="' . $data['id'] . '" /><input type="hidden" name="organization_sites_id" value="' .  $data['organization_sites_id'] . '" /><input type="hidden" name="pos" value="' . ($pos + 1) . '" /><input type="submit" name="edit" value=" " class="next" /></form>' : '')?>
	</div>
		<div class="caption"><?=(isset($data['name']) ? $data['name']. ' (' . $data['id'] . ')' : 'Add New name')?></div>
	</div>

	<?=($message ? '<div class="message' . (isset($saved) && $saved ? ' saved' : ' error') . '">' . $message . '</div>' : '')?>

	<form id="organizationForm" action="index.php" method="POST">
		<input type="hidden" name="action" value="organization" />
		<input type="hidden" name="data[id]" value="<?=($data['id'] ? $data['id'] : '')?>" />
		<input type="hidden" name="data[organization_sites_id]" value="<?=($data['organization_sites_id'] ? $data['organization_sites_id'] : '')?>" />
		<input type="hidden" name="data[setting_site_id]" value="<?=($data['setting_site_id'] ? $data['setting_site_id'] : 0)?>" />
		<input type="hidden" name="pos" value="<?=$pos?>" />
		<input type="hidden" id="save-trigger" name="save" value="" />

			<div class="infoBody" style="">

				<div class="infoColumn" style="padding: 0px 12px;">

					<div class="infoPane" style="margin-top: 12px;">

						<table class="" style="width: 100%;" cellpadding="0" cellspacing="0" border="0">

							<tbody>

							<tr>

								<td colspan="2" class="infoTitle" style="width: 342px;"><h2>Organization Profile</h2></td>

								<td colspan="2" class="infoTitle" style="width: 344px; padding-left: 12px;"><h2></h2></td>

							</tr>

							<tr>

								<td class="infoLabel" style="width: 96px; padding: 4px 0px 4px 12px;">Organization Name:*</td>

								<td class="infoText borderRight"><?= $organization_name->displaySelect('data[organization_name_id]', (isset($data['organization_name_id']) ? $data['organization_name_id'] : ''), ' ', 3, true) ?></td>


								<td class="infoLabel" style="padding: 4px 0px 4px 28px;"></td>

								<td class="infoText" style=""></td>

							</tr>

							<tr>

								<td class="infoLabel" style="padding: 4px 0px 4px 12px;">Site:</td>

								<td class="infoText borderRight" style=""><input type="text" style="width: 180px;" name="data[site]" value="<?= $data['site'] ?>" class="required" ></td>


								<td class="infoLabel" style="padding: 4px 0px 4px 28px;"></td>

								<td class="infoText" style=""></td>

							</tr>

							<tr>

								<td class="infoLabel" style="padding: 4px 0px 4px 12px;">Organization Type:</td>

								<td class="infoText borderRight" style=""><?= $type->displaySelect('data[organization_type_id]', (isset($data['organization_type_id']) ? $data['organization_type_id'] : ''), ' ', 3, true) ?></td>



								<td class="infoLabel" style="width: 116px; padding: 4px 0px 4px 28px;"></td>

								<td class="infoText" style=""></td>

							</tr>

							<tr>

								<td colspan="2" style="width: 50%; padding-bottom: 8px; border-bottom: 1px solid silver;"></td>

								<td colspan="2" style="padding-bottom: 8px; border-bottom: 1px solid silver;"></td>

							</tr>

							<tr>

								<td colspan="4" class="infoTitle"><h2>Contact Information</h2></td>

							</tr>

							<tr>

								<td class="infoLabel" style="padding: 4px 0px 4px 12px;">Address:</td>
								<td class="infoText" style=""><input type="text" style="width: 180px;" name="data[address]" value="<?= $data['address'] ?>" ></td>

								<td class="infoLabel" style="padding: 4px 0px 4px 28px;">Primary Phone:*</td>

								<td class="infoText" style=""><input type="text" style="width: 180px;" name="data[primary_phone]" value="<?= $data['primary_phone'] ?>" class="required" ></td>

							</tr>

							<tr>

								<td class="infoLabel" style="padding: 4px 0px 4px 12px;">City:</td>

								<td class="infoText" style="">
									<div style="display:inline-block;" class="setting-autosuggest">
										<input type="hidden" name="city_id" class="autosuggest-value" />
										<input
											
											name="data[city]"
											value="<?=$data['city']?>"
											class="autosuggest-input rounded"
											placeholder="Type city name"
											data-query-string="action=settings&type=city&search="
											autocomplete="off" />
										<div class="autosuggest-selection-container"></div>
									</div>
								</td>

								<td class="infoLabel" style="padding: 4px 0px 4px 28px;">Fax Number:</td>

								<td class="infoText" style=""><input type="text" style="width: 180px;" name="data[fax]" value="<?= $data['fax'] ?>" class="required" ></td>

							</tr>

							<tr>
								<td class="infoLabel" style="padding: 4px 0px 4px 12px;">State:</td>

								<td class="infoText" style="">
									<input type="text" style="width: 70px; float: left;" name="data[state]" value="<?php if(isset($data['state']) && !empty($data['state'])){ echo $data['state'];}else{ echo 'UT'; } ?>" >



									<div class="infoLabel" style="float: left; padding-left: 19px; padding-right: 7px;">Zip:</div>

									<input type="text" style="width: 38px; float: left;" class="county-lookup" name="data[zip]" value="<?= $data['zip'] ?>" >
								</td>

								<td class="infoLabel" style="padding: 4px 0px 4px 28px;">Website:</td>
								<td class="infoText" style=""><input type="text" style="width: 180px;" name="data[website]" value="<?= $data['website'] ?>" ></td>

							</tr>

							<tr>

								<td class="infoLabel" style="padding: 4px 0px 8px 12px;">
									<div>County:*</div>
								</td>

								<td class="infoText">
									<div style="display:inline-block;" class="setting-autosuggest">
										<input type="hidden" name="county_id" class="autosuggest-value" />
										<input
											
											name="data[county]"
											value="<?=$data['county']?>"
											class="autosuggest-input rounded"
											placeholder="Type a county name"
											data-query-string="action=settings&type=county&search="
											autocomplete="off" />
										<div class="autosuggest-selection-container"></div>
									</div>
								</td>

								<td class="infoLabel" style="padding: 4px 0px 4px 28px;"></td>
								<td></td>

							</tr>

							<tr>

								<td colspan="2" style="width: 50%; padding-bottom: 8px; border-bottom: 1px solid silver;"></td>

								<td colspan="2" style="padding-bottom: 8px; border-bottom: 1px solid silver;"></td>

							</tr>

							<tr>

								<td colspan="2" class="infoTitle borderRight" style="width: 342px;"><h2>Program Information</h2></td>
								<td colspan="2" class="infoTitle borderRight" style="width: 342px;"><h2>Partnership Information</h2></td>

							</tr>

							<tr>

								<td class="infoLabel" style="width: 96px; padding: 4px 0px 4px 12px;">Region:</td>

								<td class="infoText borderRight">
									<? $showAllRegions = (is_numeric($data['id']) ? true : false) ?>
									<?= $region->displaySelect('data[region_id]', ($data['region_id'] ? $data['region_id'] : ''), ' ', 20, '', $showAllRegions) ?>
								</td>

								<td class="infoLabel" style="width: 96px; padding: 4px 0px 4px 0px;">MOU:</td>

								<td class="infoText borderRight">
									<?= $organization->displayEnumOptions('data[mou]', 'mou', (!empty($data['mou']) && $data['mou'] == 'Yes' ? $data['mou'] : 'No'), 33) ?>
								</td>

							</tr>

							<tr>

								<td class="infoLabel" style="text-align: top; padding: 4px 0px 4px 12px;">Status:</td>

								<td class="infoText">
									<?= $status->displaySelect('data[status]', (isset($data['status']) ? $data['status'] : ''), ' ', 21, false, NULL, true) ?>
								</td>

								<td class="infoLabel" style="width: 96px; padding: 4px 0px 4px 0px;">Partnership Level:</td>

								<td class="infoText borderRight">
									<?= $partnership->displaySelect('data[partnership_level_id]', $data['partnership_level_id'], ' ', 27, false, NULL, true) ?>
								</td>

							</tr>

							<tr>

								<td class="infoLabel" style="text-align: top; padding: 4px 0px 4px 12px;">Service Area:</td>

								<td class="infoText">
									<? $area = isset($data['service_area']) ? explode(', ', $data['service_area']) : array();
										if(!is_array($area))
											$area = array();
									?>
									<?= $county->displaySelect('data[service_area]', $area, ' ', 22, false, 'chosen-select', true) ?>
								</td>

								<td class="infoLabel" style="width: 96px; padding: 4px 0px;">Date Last Signed: </td>

								<td class="infoText borderRight">
									<input type="text" name="data[date_last_signed]" value="<?= (isset($data['date_last_signed']) && $data['date_last_signed_formatted'] != '00/00/0000' && $data['date_last_signed_formatted'] != '12/31/1969' ? $data['date_last_signed_formatted'] : '') ?>" class="date permission" placeholder="mm/dd/yyyy"  />
								</td>

							</tr>

							<tr>

								<td class="infoLabel" style="text-align: top; padding: 4px 0px 4px 12px;"></td>

								<td class="infoText"></td>

								<td class="infoLabel" style="text-align: top; padding: 4px 0px;">
									Partnership Notes:
								</td>

								<td id="provider-autosuggest" class="infoText">
									<textarea name="data[partnership_notes]" cols="40" rows="3" style="width: 188px;" ><?= $data['partnership_notes'] ?></textarea>
								</td>

							</tr>

							

							<tr>

								<td colspan="2" style="width: 50%; padding-bottom: 8px; border-bottom: 1px solid silver;"></td>

								<td colspan="2" style="padding-bottom: 8px; border-bottom: 1px solid silver;"></td>

							</tr>

							<tr>

								<td colspan="4" class="infoTitle"><h2>Additional Information</h2></td>

							</tr>

							<tr>

								<td class="infoLabel" style="width: 96px; padding: 4px 0px 4px 12px;">Mode of Initial Contact:</td>

								<td class="infoText borderRight">
									<?= $mode_of_contact->displaySelect('data[mode_of_contact_id]', (isset($data['mode_of_contact_id']) ? $data['mode_of_contact_id'] : ''), ' ', 30) ?>
								</td>

								<td class="infoLabel" style="width: 96px; padding: 4px 0px 4px 28px;">Success Story:</td>

								<td class="infoText borderRight">
									<?= $organization->displayEnumOptions('data[success_story]', 'success_story', (!empty($data['success_story']) && $data['success_story'] == 'Yes' ? $data['success_story'] : 'No'), 33) ?>
								</td>

							</tr>

							<tr>

								<td class="infoLabel" style="width: 96px; padding: 4px 0px 4px 12px;">Resource Database</td>

								<td class="infoText borderRight">
									<?= $resource_database->displaySelect('data[resource_database_id]', (isset($data['resource_database_id']) ? $data['resource_database_id'] : ''), ' ', 31) ?>
								</td>

								<td class="infoLabel" style="text-align: top; padding: 4px 0px 4px 28px;">Success Story Notes:</td>

								<td class="infoText" rowspan="2">
									<textarea name="data[success_story_notes]" cols="40" rows="3" style="width: 188px;" ><?= $data['success_story_notes'] ?></textarea>
								</td>

							</tr>

							<tr>

								<td class="infoLabel" style="text-align: top; padding: 4px 0px 4px 12px;">ID #:</td>

								<td class="infoText">
									<input type="text" style="width: 180px;" name="data[database_id]" value="<?= !empty($data['database_id']) ? $data['database_id'] : '' ?>" >
								</td>

								<td class="infoLabel" style="width: 96px; padding: 4px 0px 4px 28px;"></td>

								<td class="infoText borderRight"></td>

							</tr>

							<tr>

								<td class="infoLabel" style="width: 96px; padding: 4px 0px 4px 12px;"></td>

								<td class="infoText borderRight"></td>

								<td class="infoLabel" style="text-align: top; padding: 4px 0px 4px 28px;">Service Terms:</td>

								<td class="infoText" rowspan="2">
								
									<? 
									$org_id=$organization->getOrganizationByOrgID($data['organization_name_id']);
									if(!empty($data['service_terms']))
									{
										$string = $data['service_terms'];	
									}
									else{
										$string = $org_id['service_terms'];	
									}
									$terms = isset($string) ? explode(',', $string) : array();
										if(!is_array($terms))
											$terms = array();
									?>
									<?= $service_terms->displaySelect('data[service_terms]', $terms, ' ', 37, false, 'chosen-select', true) //201016 ?>
								</td>

							</tr>

							<tr>

								<td colspan="2" style="width: 50%; padding-bottom: 8px; border-bottom: 1px solid silver;"></td>

								<td colspan="2" style="padding-bottom: 8px; border-bottom: 1px solid silver;"></td>

							</tr>

							<tr>

								<td colspan="4">

									<div id="childrenDiv" class="" style="margin: 14px 0 14px 0;">

										<div class="title"><h2>Providers</h2></div>

										<? $tabIndex = 50; // tab index is incremented from here on out ?>
										<? $childIncrement = null; ?>
										<? if(isset($data['contacts']) && is_array($data['contacts'])) : //echo "<pre>";print_r($data);die;?>
										<? foreach($data['contacts'] as $child) : ?>
											<? 
												$prenatalChecked = false;
												if (!empty($child['birth_due_date_formatted']) 
													&& $child['birth_due_date_formatted'] !== '0000-00-00') 
												{
													$prenatalChecked = true;
												}
												if(isset($child["birth_due_date"]) && !empty($child["birth_due_date"]) && !$prenatalChecked) {
													$prenatalChecked = true;
												}
											?>
											<? if(!isset($child['id'])) : ?>
												<? $childIncrement++; $child['id'] = 'NEW' . $childIncrement; ?>
												<script>newChildCurrentIndex='<?=$childIncrement?>';</script>
											<? endif; ?>

										      <input type="hidden" name="children[<?= $child["id"] ?>][id]" value="<?= $child['id'] ?>" />
												<table class="infoTable edit editChild" border="0" cellspacing="0" cellpadding="0" style="margin-top: 4px; width: 100%; border-color: silver; border-style: solid; border-width: 1px 1px 0px 1px;">

													<tbody>
													<tr>

														<th class="borderRight smallHeader">First Name</th>
														<th class="borderRight smallHeader">Last Name</th>
														<th class="borderRight smallHeader">Title</th>
														<th class="borderRight smallHeader">Gender</th>
														<th class="borderRight smallHeader">Email</th>
														<th class="borderRight smallHeader">Office Phone</th>
														<th class="borderRight smallHeader">Cell Phone</th>
														<th class="borderRight smallHeader">Type of Provider</th>
														<td class="btn-background" style="padding: 0 5px; width: 26px; height: 25px;">
															<a href="#child-delete-div" class="fancybox delete-name"><input type="button" class="btn-small" name="deleteChild[<?= $child['id'] ?>]" value="Delete" tabindex="-1" /></a>

														</td>

													</tr>

													<tr>

														<td class="borderLeft borderTop" style="vertical-align: top;">

															<input type="text" style="width: 120px;" name="children[<?= $child["id"] ?>][first]" value="<?= $child["first"] ?>" tabindex="<?= $tabIndex++ ?>" />

														</td>

														<td class="borderLeft borderTop" style="vertical-align: top;">

															<input type="text" style="width: 120px;" name="children[<?= $child["id"] ?>][last]" value="<?= $child["last"] ?>" tabindex="<?= $tabIndex++ ?>" />

														</td>

														<td class="borderTop" style="text-align: center;">
															<input type="text" style="width: 120px;" name="children[<?= $child["id"] ?>][title]" value="<?= $child["title"] ?>" tabindex="<?= $tabIndex++ ?>" />	
														</td>

														<td class="borderTop" style="border-style: solid; text-align: center;">

															<select name="children[<?= $child["id"] ?>][gender]" tabindex="<?= $tabIndex++ ?>">

																<option></option>

																<option<?= $child['gender'] == 'F' ? ' selected="selected"' : '' ?>>F</option>

																<option<?= $child['gender'] == 'M' ? ' selected="selected"' : '' ?>>M</option>

															</select>

														</td>
														<td class="borderTop" style="border-style: solid; text-align: center;">

															<input type="text" name="children[<?= $child["id"] ?>][email]" value="<?= ($child["email"] ? $child["email"] : ''); ?>" style="width: 100px;" tabindex="<?= $tabIndex++ ?>">

														</td>
														<td class="borderTop" style="border-style: solid; text-align: center;">
															<input type="text" name="children[<?= $child["id"] ?>][office_phone]" value="<?= ($child["office_phone"] ? $child["office_phone"] : ''); ?>" style="width: 100px;" tabindex="<?= $tabIndex++ ?>" />

														</td>

														<td class="borderTop" style="border-style: solid; text-align: center;">

															<input type="text" name="children[<?= $child["id"] ?>][cell_phone]" value="<?= ($child["cell_phone"] ? $child["cell_phone"] : ''); ?>" style="width: 100px;" tabindex="<?= $tabIndex++ ?>">

														</td>

														<td class="borderTop" colspan="2" style="padding-right: 10px;">
															<?=
																$type_of_contact->displaySelect(
																	'children[' . $child["id"] . '][type_of_contact_id]',
																	(isset($child['type_of_contact_id']) ?
																		$child['type_of_contact_id'] :
																		''
																	),
																	' ',
																	$tabIndex++
																)
															?>
														</td>

													</tr>
													<tr>
														<td colspan="8" class="borderLeft borderRight borderBottom borderTop" style="height: 34px; background-color: white;">
															<div class="infoText" style="clear: left;">
																<span class="infoLabel" style="font-weight: bold;">Notes:&nbsp;&nbsp;</span><br />
																<textarea name="children[<?= $child["id"] ?>][notes]" cols="125" rows="2" tabindex="<?= $tabIndex++ ?>"></textarea>
															</div>
														</td>
													</tr>
													

												</tbody></table>

										<? endforeach; ?>
										<? endif; ?>

										<!-- New Child -->
										<table class="infoTable edit newChild" border="0" cellspacing="0" cellpadding="0" style="margin-top: 4px; width: 100%; border-color: silver; border-style: solid; border-width: 1px 1px 0px 1px;">

										<tbody><tr style="background: #ece6e6;">

											<th class="borderRight smallHeader">First Name</th>
											<th class="borderRight smallHeader">Last Name</th>
											<th class="borderRight smallHeader">Title</th>
											<th class="borderRight smallHeader">Gender</th>
											<th class="borderRight smallHeader">Email</th>
											<th class="borderRight smallHeader">Office Phone</th>
											<th class="borderRight smallHeader">Cell Phone</th>
											<th class="borderRight smallHeader">Type of Provider</th>
											<td style="padding: 0 5px; width: 26px; height: 25px;">

												<input type="button" class="deleteAnotherChild btn-small" name="deletechild" value="Delete" tabindex="-1">

											</td>

										</tr>

										<tr>

											<td class="borderLeft borderTop" style="vertical-align: top;">

												<input type="text" style="width: 120px;" name="template[0][first]" value="" tabindex="<?= $tabIndex++ ?>">

											</td>

											<td class="borderLeft borderTop" style="vertical-align: top;">

												<input type="text" style="width: 120px;" name="template[0][last]" value="" tabindex="<?= $tabIndex++ ?>">

											</td>

											<td class="borderTop" style="text-align: center;">
												<input type="text" style="width: 120px;" name="template[0][title]" value="" tabindex="<?= $tabIndex++ ?>">
											</td>

											<td class="borderTop" style="border-style: solid; text-align: center;">

												<select name="template[0][gender]" tabindex="<?= $tabIndex++ ?>">

													<option></option>

													<option>F</option>

													<option>M</option>

												</select>

											</td>

											<td class="borderTop" style="border-style: solid; text-align: center;">

												<input type="text" name="template[0][email]" style="width: 100px;" tabindex="<?= $tabIndex++ ?>">

											</td>
											<td class="borderTop" style="border-style: solid; text-align: center;">

												<input type="text" name="template[0][office_phone]" style="width: 100px;" tabindex="<?= $tabIndex++ ?>">

											</td>
											<td class="borderTop" style="border-style: solid; text-align: center;">

												<input type="text" name="template[0][cell_phone]" style="width: 100px;" tabindex="<?= $tabIndex++ ?>">

											</td>

											<td class="borderTop" colspan="2" style="padding-right: 10px;">
												<?= $type_of_contact->displaySelect('template[0][type_of_contact_id]', '', ' ',  $tabIndex++) ?>

											</td>

										</tr>
										<tr>
											<td colspan="9" class="borderLeft borderRight borderBottom borderTop" style="height: 34px; background-color: white;">
												<div class="infoText" style="clear: left;">
													<span class="infoLabel" style="font-weight: bold;">Notes:&nbsp;&nbsp;</span><br>
													<textarea name="template[0][notes]" cols="125" rows="2" class="birth not_count" tabindex="<?= $tabIndex++ ?>"></textarea>
												</div>
											</td>
										</tr>
										

									</tbody></table>

									</div>
								</td>

							</tr>

							<tr>
								<td colspan="4" style="padding-top: 8px">
									<input type="button" name="addAnotherChild" value="Add Provider" class="addAnotherChild btn-small" tabindex="990" />
								</td>
							</tr>

							<tr>

								<td colspan="4" style="padding-top: 8px;"></td>
							</tr>


							<tr>

								<td colspan="4">
								<span class="infoLabel" style="font-weight: bold;">Organization Notes:&nbsp;&nbsp;</span><br>
								<textarea name="note" cols="128" rows="1" style="width: 100%; height: 16px; line-height: 16px;" tabindex="1000"><?//= (isset($_REQUEST['note']) ? $_REQUEST['note'] : $data['note']) ?></textarea>
								</td>

							</tr>

							<tr>

								<td colspan="4" style="padding-top: 8px;"></td>


							<tr>
								<td colspan="4" style="text-align: right;">
									<input type="button" name="savebutton" value="Save" class="btn-small save-form" tabindex="1020" />
									<? if($data['id']) : ?>
									<input type="button" name="delete" value="Delete" class="btn-small delete-organization" tabindex="1030" />
									<? endif; ?>
								</td>
							</tr>

							<tr>

								<td colspan="4" style="padding-top: 8px;"></td>

							</tr>

						</tbody></table>



					</div>

				</div>

			</div>

		</form>


</div>

<!-- popup to delete contact records starts -->
<div style="display:none;" id="child-delete-div">		
	<div style="padding: 0 10px;" class="titleBar"><span style="" class="caption">Delete Contact</span></div>
	<div style="padding: 10px">
		<div style="color:red;font-size:16px;padding:10px;">
			Are you sure you want to delete this contact?
		</div>
		<input type="button" class="btn-small delete-child" style="margin: 10px 10px 0;" value="Yes">
		<input type="button" class="btn-small cancel-delete" value="Cancel">
	</div>
		
</div>
	<!-- popup to delete contact records ends -->

<!-- popup to delete contact records for new addition starts -->
<div style="display:none;" id="new-child-delete-div">		
	<div style="padding: 0 10px;" class="titleBar"><span style="" class="caption">Delete Contact</span></div>
	<div style="padding: 10px">
		<div style="color:red;font-size:16px;padding:10px;">
			Are you sure you want to delete this contact?
		</div>
		<input type="hidden" id="new_child_ref">
		<input type="button" class="btn-small new-delete-child" style="margin: 10px 10px 0;" value="Yes">
		<input type="button" class="btn-small cancel-delete" value="Cancel">
	</div>
		
</div>
	<!-- popup to delete contact records for new addition  ends -->
