<script type="text/javascript">
$("document").ready(function(){
	$(".provider").on("click", function(){
		var id = $(this).attr('id').slice(9);
		location.href="index.php?action=provider&id=" + id;
	});
	$(".sort").on("click", function(){
		field = ($(this).text().replace(/ /g, '_').toLowerCase());
		if($(this).hasClass('sorting_asc')){
			$(this).removeClass('sorting_asc').addClass('sorting_desc');
			fieldsort = 'desc';
		}
		else if($(this).hasClass('sorting_desc')){
			$(this).removeClass('sorting_desc').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		else {
			$(this).removeClass('sorting').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		if(field == 'name'){
			field = 'last_name';
		}
		if(field == 'provider_role'){
			field = 'role';
		}
		if(field == 'clinic/organization_name'){
			field = 'employer';
		}
		location.href="index.php?action=providers&print=true&field="+field+"&sort="+fieldsort;
	});
	$(document).on('click', '#print-list', function(e){
		e.preventDefault();
		postString = $('#filter-form').serialize();
		window.open('index.php?print=true&' + postString, '');
	});
	$(document).on('click', '#export-list', function(e){
		e.preventDefault();
		postString = $('#filter-form').serialize();
		window.open('index.php?export=true&' + postString, '');
	});
});
</script>
<? if(is_array($providers)) : ?>	
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="grid">
	<thead>
		<tr>
			<th class="sort sorting<?=($sorts['employer'] ? '_' . strtolower($sorts['employer']) : '')?>">Clinic/Organization Name</th>
			<th class="sort sorting<?=($sorts['last_name'] ? '_' . strtolower($sorts['last_name']) : '')?>">Name</th>
			<th class="sort sorting<?=($sorts['title'] ? '_' . strtolower($sorts['title']) : '')?>">Title</th>
			<th class="sort sorting<?=($sorts['role'] ? '_' . strtolower($sorts['role']) : '')?>">Provider Role</th>
			<th class="sort sorting<?=($sorts['city'] ? '_' . strtolower($sorts['city']) : '')?>">City</th>
			<th class="sort sorting<?=($sorts['phone'] ? '_' . strtolower($sorts['phone']) : '')?>">Phone</th>
			<th class="sort sorting<?=($sorts['email'] ? '_' . strtolower($sorts['email']) : '')?>">Email</th>
		</tr>
	</thead>
	<tbody>
	<? $row = 'odd'; ?>
	<? foreach($providers as $provider) : ?>
	
		<tr id="provider_<?=$provider['id']?>" class="provider <?=$row?>">
			<td><?=$provider['employer']?></td>
			<td><?=ucfirst(strtolower($provider['last_name'])) . ', ' . $provider['first_name']?></td>
			<td><?=$provider['title']?></td>
			<td><?=$provider['role']?></td>
			<td><?=$provider['city']?></td>
			<td><?=$provider['phone']?></td>
			<td><?=($provider['email'] ? '<a href="mailto:' . $provider['email'] . '" title="' . $provider['email'] . '">Email</a>' : '')?></td>
		</tr>
		
		<? if($row=='odd'){ $row = 'even'; } else { $row='odd'; }?>
		
	<? endforeach; ?>
	</tbody>
</table>
<div class="gridFooter">
	<div style="float: left;" id="gridPaginationText">
		Showing <?= $firstRecord ?>-<?= $lastRecord ?> of  <?= $totalProviders ?> providers
	</div>
</div>
<? else : ?>
<p><br /><em>No result found.</em></p>
<? endif; ?>