<style>
.popupFooter{
	float:right;
}
select, input, textarea {
    font-size: 11px !important;
    font-weight: normal !important;
    color: #555 !important;
    border: 1px inset silver !important;
    padding: 4px;
}
</style>
<script type="text/javascript">
$("document").ready(function(){
	$('.fancybox').fancybox({
		padding : '0px',        
        scrolling : 'no',
		afterClose: function(){
	    
	    }
	});
	<?php 
	if(isset($_GET['showBuilder']) && $_GET['showBuilder']='true'){?>
	$( "#showCreateReport" ).trigger( "click" );
	$.fancybox.open('#report_new');
	
	<?php }?>
	$("#showCreateReport").on('click',function(){
		$.fancybox.open('#report_new');	
	});
	
	$("#hideCreateReport").on('click',function(){
		
		$.fancybox.close();
	});

	$(".report").on("click", function(){
		var id = $(this).attr('id');
		
		location.href="index.php?action=report&do=reGenerate&reportID=" + id;
	});
	$(".sort").on("click", function(){
		field = ($(this).text().replace(/ /g, ''));
		if($(this).hasClass('sorting_asc')){
			$(this).removeClass('sorting_asc').addClass('sorting_desc');
			fieldsort = 'desc';
		}
		else if($(this).hasClass('sorting_desc')){
			$(this).removeClass('sorting_desc').addClass('sorting_asc');
			fieldsort = 'asc';
		} 
		else {
			$(this).removeClass('sorting').addClass('sorting_asc');
			fieldsort = 'asc';
		}
		if(field == 'ReportName'){
			field = 'Name';
		}
		if(field == 'Category'){
			field = 'ReportCategoryID';
		}
		if(field == 'LastGenerated'){
			field = 'LastGenerated';
		}
		if(field == 'DateCreated'){
			field = 'Created';
		}
		location.href="index.php?action=report&field="+field+"&sort="+fieldsort;
	});
	$(document).on('click', '#print-list', function(e){
		e.preventDefault();
		postString = $('#filter-form').serialize();
		window.open('index.php?print=true&' + postString, '');
	});
	$(document).on('click', '#export-list', function(e){
		e.preventDefault();
		postString = $('#filter-form').serialize();
		window.open('index.php?export=true&' + postString, '');
	});
	jQuery("#copyFrom").change(function(){
		if (jQuery("#copyFrom").val() == ""){
			jQuery("#category").attr('disabled', ''); 
			jQuery("#layout").attr('disabled', ''); 
		} else {
			jQuery("#category").attr('disabled', 'disabled'); 
			jQuery("#layout").attr('disabled', 'disabled'); 
		}
		
	});
});
function createReport(){
	if($("#reportName").val()==''){
		alert("Report name should not be blank");
		return false;
	}else{
		return true;
	}	
}
</script>
<!--script src="js/protoaculous.js"></script-->
<script src="js/ext-prototype-adapter.js"></script>
<script src="js/ext-all.js"></script>
<script src="js/builder.js"></script>
<div class="pageTitleBar">
	<h1>User Defined Reports</h1>	
	<div style="float: right; padding: 0px 4px 4px 0; margin-left: 30px;">
		<form action="index.php">
		<input type="hidden" name="action" value="report" />
		<input type="hidden" name="reportID" value="new" />
		<input type="button" name="showCreateReport" id="showCreateReport" value="Add Report" class="fancybox_report btn-small" /></form>
	</div>	
			
</div>	

<div id="report_new" style="display: none;width:500px;">
	<div class="titleBar" style="padding-left: 10px;"><span class="caption" style="">New Report</span></div>
	<script type="text/javascript">
				
				var reportMargins = new Array();
				<? foreach ($reportsAll as $report) { ?>
					<?
						$rm = explode('|', $report['Margins']);
					?>
					reportMargins[<?=$report['ReportID']?>] = {mtop: '<?=$rm[0]?>', mright: '<?=$rm[1]?>', mbottom: '<?=$rm[2]?>', mleft:'<?=$rm[3]?>', showHeader: '<?=$report['ShowHeader']?>'};
				<? } ?>
				
				function loadPresets(whichID) {
					jQuery('input[name="topMargin"]').val(reportMargins[whichID].mtop);
					jQuery('input[name="rightMargin"]').val(reportMargins[whichID].mright);
					jQuery('input[name="bottomMargin"]').val(reportMargins[whichID].mbottom);
					jQuery('input[name="leftMargin"]').val(reportMargins[whichID].mleft);
					jQuery('input[name="showHeader"]').attr('checked', (reportMargins[whichID].showHeader == '1' ? 'checked' : ''));
				}
			</script>
	<form method="POST">
	<input type="hidden" name="do" value="createReport">
	<input type="hidden" name="action" value="report">
		<div class="fieldGroup" style="width: 100%;">
			<div class="fieldSet">
				<div class="label">Report Name:</div>
				<input type="text" name="name" id="reportName" class="field">
			</div>
					
			<div class="fieldSet">
				<div class="label">Copy Report From:</div>
				<select name="copyFrom" id="copyFrom" class="field" onchange="loadPresets(jQuery('option:selected', jQuery(this)).val())">
					<option value="">Create New</option>
					<? foreach($reportsAll as $report) { ?>
						<option value="<?=$report['ReportID']?>"><?=$report['Name']?></option>
					<? } ?>
				</select>
			</div> 
					
			<div class="fieldSet">
				<div class="label">Category:</div>
				
				<select name="reportCategoryID" id="category" class="field">
					<? foreach($reportCategories as $reportCategory) { ?>
						<option value="<?=$reportCategory['ReportCategoryID'];?>"><?=$reportCategory['Name']?></option>
					<? } ?>
				</select>
			</div>
					
			<div class="fieldSet">
				<div class="label">Layout:</div>
				<select id="layout" name="layoutType" class="field">
					<option value="0">Portrait 8.5" X 11"</option>
					<option value="1">Landscape 11" X 8.5"</option>
				</select>
			</div>
					
			<div class="fieldSet">
				<div class="label">Margins (in inches):</div>
				<div class="field">
					<div class="subLabel">Top: </div><input type="text" name="topMargin" class="subField" value=".25">
					<div class="subLabel">Bottom: </div><input type="text" name="bottomMargin" class="subField" value=".25">
					
				</div>
			</div>
					
			<div class="fieldSet">
				<div class="label">&nbsp;</div>
				<div class="field">
					<div class="subLabel">Left: </div><input type="text" name="leftMargin" class="subField" value=".25">
					<div class="subLabel">Right: </div><input type="text" name="rightMargin" class="subField" value=".25">
				</div>
			</div>
					
			<div class="fieldSet">
				<div class="label" style="float:left">Show Header:</div>
				<input type="checkbox" name="showHeader" value="1" style="margin-left: 20px;   margin-top: 3px;">
			</div>
		</div>
		<hr>
		<div class="popupFooter">
			<input type="button" value="Cancel" id="hideCreateReport">
			<input type="submit" value="Continue" onClick="return createReport();">
		</div>
		<hr>
</form>
</div>

<div class="dataTable" style="height: auto;">
	

<? if(is_array($reports)) : ?>	
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="grid">
	<thead>
		<tr>
			<th class="sort sorting<?=(isset($sorts['Name']) ? '_' . strtolower($sorts['Name']) : '')?>">Report Name</th>
			<th class="sort sorting<?=(isset($sorts['Category']) ? '_' . strtolower($sorts['Category']) : '')?>">Category</th>
			<th class="sort sorting<?=(isset($sorts['LastGenerated']) ? '_' . strtolower($sorts['LastGenerated']) : '')?>">Last Generated</th>
			<th class="sort sorting<?=(isset($sorts['Created']) ? '_' . strtolower($sorts['Created']) : '')?>">Date Created</th>
		</tr>
	</thead>
	<tbody>
	<? $row = 'odd'; ?>
	<? foreach($reports as $report) : ?>	
		<tr id="<?=$report['ReportID']?>" class="report <?=$row?>">
			<td><?=(($report['Name']))?></td>
			<td><?=(($report['Category']))?></td>
			<td><?=$report['LastGenerated']?></td>
			<td><?=$report['Created']?></td>		
		</tr>
		
		<? if($row=='odd'){ $row = 'even'; } else { $row='odd'; }?>
		
	<? endforeach; ?>
	</tbody>
</table>
<div class="gridFooter">
	<div style="float: left;" id="gridPaginationText">
		Showing <?= $firstRecord ?>-<?= $lastRecord ?> of  <?= $totalApplicants ?> reports
	</div>
	<div style="float: right;" id="gridPages">
		<a href="index.php?action=report">First</a>			
		<?= ($pageNumber > 1 ? '<a href="index.php?action=report' . (isset($_REQUEST['field']) ? '&field=' . $_REQUEST['field'] . (isset($_REQUEST['sort']) ? '&sort=' . $_REQUEST['sort'] : '') : '') . '&page= ' . ($pageNumber - 1) . '">&lt; Prev</a>' : '')?>			
		Page <?= $pageNumber ?> of <?= $numPages ?>			
		<?= ($pageNumber < $numPages ? '<a href="index.php?action=report' . (isset($_REQUEST['field']) ? '&field=' . $_REQUEST['field'] . (isset($_REQUEST['sort']) ? '&sort=' . $_REQUEST['sort'] : '') : '') . '&page= ' . ($pageNumber + 1) . '">Next &gt;</a>' : '')?>			
		<a href="index.php?action=report<?= (isset($_REQUEST['field']) ? '&field=' . (isset($_REQUEST['field']) ? '&field=' . $_REQUEST['field'] : '' ) . ($_REQUEST['sort'] ? '&sort=' . $_REQEST['sort'] : '') : '') ?>&page=<?= $numPages ?>">Last</a>
	</div>
</div>
<? else : ?>
<p><br /><em>No result found.</em></p>
<? endif; ?>