<style>
    .hide-hmg-worker{display:none;}
    select,input[type="text"]{height:25px;}
    td{padding:2px 0px;}
</style>
<script type="text/javascript">

var newChildCurrentIndex = 0;
    
    function getHowHeardDetails(heard_id){
	var select = '';
	$.ajax({
		url: 'index.php',
		data: {
			action:'setting',
			'get-select': true,
			//'selected': selected,
			'heard_id' : heard_id
		},
		async: false
	}).done(function(data){
		//alert(data);
		select = data;
	});

	return select;
}
    
$("document").ready(function(){


	$('#create-report').on('click', function(e){
		e.preventDefault();
		$('#export').val('');
        $('.message').html('');
        form = $('#outreach-form');
        form.attr('target', '_blank');
        form.submit();
		
	});

	$('#export-report').on('click', function(e){	
        $('#export').val(1);
			$('.message').html('');
			form = $('#outreach-form');
			form.attr('target', '_blank');
			form.submit();		
	});

	// initialize date picker
	$('.date').datepicker();



	$('.fancybox').fancybox({
		padding : '0px', scrolling : 'no',
		afterClose: function(){
	      // fancybox is closed, run custom code
	      $('.providerAutoCompList').hide();
	    }
	});
	
    $('#family_heard_id').bind("change", function(e) {
		e.preventDefault();
		//ajax call to fetch how heard details listing
		var result = getHowHeardDetails($(this).val());
		
		if(result != ''){
			
			$('#heard_details_td').html(result).append("<script>$('.chosen-select').chosen();<\/script>");
		}
		else{
			$('#heard_details_td').html('<select class="setting"><option value=""></option></select>');
		}
	});
    
	$('.enable-multi-select').on('change', function(e){
		var checkbox = $(this);
		var select = checkbox.prev();
		if(checkbox.prop('checked')){
			select.attr('multiple', true);
			select.attr('size', 5);
			var name = select.attr('name');
			select.attr('name', name + '[]');
			select.find(':first-child').remove();
		} else {
			select.attr('multiple', false);
			select.attr('size', '');
			var name = select.attr('name');
			select.attr('name', name.replace('[]', ''));
		}
	});
	$('.js-toggle-worker-select').on('change', function(e){
		var checkbox = $(this);
		var hiddenHmgWorkerSelect = $('.hide-hmg-worker');
		var hmgWorkerSelect = $('.hmg_worker');
		hmgWorkerSelect.removeClass('hmg_worker').addClass('hide-hmg-worker');
		hmgWorkerSelect.prop('disabled', true);
		hiddenHmgWorkerSelect.addClass('hmg_worker').removeClass('hide-hmg-worker');
		hiddenHmgWorkerSelect.prop('disabled', false);
	});
	
});
</script>
<script type="text/javascript" src="js/autoCompleteProviders.js"></script>

<form id="outreach-form">
    <div class="message"><?= $message ?></div>
    <input type="hidden" name="action" value="reports" />
    <input type="hidden" name="type" value="user_defined" />
    <input type="hidden" name="subtype" value="family_grid" />
    <input type="hidden" id="export" name="export" value="" />
    <div class="pageTitleBar" style="position: relative;">
        <a href="index.php?action=reports"><h1>User Defined Reports: Family Grid</h1></a>

    </div>

    <div id="outreach-reports">
	
	   <div class="reportTitle" style="font-size: 16px;margin: 10px 0px;">Generate Report By</div>
	<?php
    
use Hmg\Models\Setting;
use Hmg\Models\Zip;
use Hmg\Models\SchoolDistrict;
use Hmg\Models\Family;
use Hmg\Helpers\SessionHelper as FilterHelper;

$family = new Family();

$relationships = new Setting('relationships');
$language      = new Setting('language');
$familyHeard   = new Setting('how_heard_category');
$callReason    = new Setting('call_reason');
$race          = new Setting('race');
$ccLevel       = new Setting('cc_level');
$ethnicity     = new Setting('ethnicity');
$issues        = new Setting('issues');
$status        = new Setting('status');
$city          = new Setting('city');
$county        = new Setting('county');
$region        = new Setting('region');
$point_of_entry= new Setting('point_of_entry');
$zip           = new zip();

$schoolDistrict = new schoolDistrict();

?>



		<table style="width: 650px;    margin: 0 auto;">
			<tbody>
				
                <tr>
                    <td class="label" style="vertical-align: top">Region </td>
					<td style="vertical-align: top">
						<?
						
                                echo $region->displaySelect('filters[region_id]', '', ' ');
							
						?>
					</td>
                    
                    <td class="label">Language: </td>
					<td>
						<?= $language->displaySelect('filters[language_id]', '', ' ') ?>
					</td>
                    
                    
                </tr>
				<tr>
					<td class="label">City: </td>
					<td>
						
						<?= $city->displaySelect('filters[city]', '', ' ', '', false, '', true) ?>
						<input type="checkbox" class="enable-multi-select" /> Multi
					</td>
                    
                    <td class="label">Race: </td>
					<td>
						<?= $race->displaySelect('filters[race_id]', '', ' ') ?>
					</td>
					
				</tr>
				<tr>
                    
                    <td class="label">Zip: </td>
					<td>
						<?= $zip->displaySelect('filters[zip]', '', ' ', '', false, '', true) ?>
						<input type="checkbox" class="enable-multi-select"  /> Multi
					</td>
                    
                    <td class="label">Ethnicity: </td>
					<td>
						<?= $ethnicity->displaySelect('filters[ethnicity_id]', '', ' ') ?>
					</td>
					
					
				</tr>
				<tr>
                    
                    <td class="label">School District </td>
					<td>
						<?= $schoolDistrict->displaySelect("filters[school_district]", '', 'School District') ?>
					</td>
					<td class="label">How Heard Category: </td>
					<td>
						<?= $familyHeard->displaySelect('filters[family_heard_id]', '', ' ', 31, false, null, true, false, false, 'family_heard_id') ?>
					</td>
					
				</tr>
				<tr>
					
                    <td class="label">Status: </td>
					<td>
						<?= $status->displaySelect('filters[status]', '', ' ', '', false, NULL, false, true) ?>
					</td>
					<td class="label" style="">How Heard Details</td>
                    <td class="infoText" id="heard_details_td">
                        
                        <select class="setting"><option value=""></option></select>
                        
                    </td>
					
				</tr>
				<tr>
					<td class="label">Start Date: </td>
					<td>
						<input type="text" class="date" id="adv-start-date" name="filters[start_date]" value="" placeholder="Start Date" />
						<input type="text" class="date" id="adv-end-date" name="filters[end_date]" value="" placeholder = "End Date" />
					</td>
                    <td class="label">Point of Entry: </td>
					<td>
						<?= $point_of_entry->displaySelect('filters[point_of_entry]', '', ' ', 50) ?>
					</td>
					
					
				</tr>
				<tr>
					<td class="label">CC Level: </td>
					<td>
						<?= $ccLevel->displaySelect('filters[cc_level]', '', ' ', '', false, null, false) ?>
					</td>
					<td class="label">Reason for Call: </td>
					<td>
						<?= $callReason->displaySelect('filters[call_reason_id]', '', ' ') ?>
					</td>
					
				</tr>
				<tr>
					
                    <td class="label">Worker: </td>
					<td>
						<?= $family->displayHmgWorkerSelect('filters[hmg_worker]', '', 'all') ?>
						<?= $family->displayHmgWorkerSelect('filters[hmg_worker]', '', 'all', '', 'hide-hmg-worker', true) ?>
						<input type="checkbox" class="js-toggle-worker-select"> All
					</td>
                    
					<td class="label" style="vertical-align: top">Referral Issue: </td>
					<td style="vertical-align: top">
						<?= $issues->displaySelect('filters[issue]', '', ' ') ?>
					</td>

				</tr>			
				
			</tbody>
		</table>
	   
        <div id="filter-form" action="index.php" style="width:60%;margin:30px 0px; text-align:right;">
            <input type="submit" id="create-report" value="Create Report" class="btn-small" />
            <input type="submit" id="export-report" value="Export Report" class="btn-small" />
        </div>


    </div>
</form>
