<div class="pageTitleBar">
	<h1>Reports</h1>
</div>
<style>
#report-links a {
	font-size: 10pt;
	line-height: 18pt;
	color: #000;
}
</style>
<div id="report-links">

    <a href="index.php?action=reports&type=annual&subtype=hmg-export">Annual Reports</a><br>
    <a href="index.php?action=reports&type=outreach">Outreach Reports</a><br>
    <a href="index.php?action=reports&type=referral">Referral Reports</a><br>
    <a href="index.php?action=report">User Defined Reports</a> 

</div>