<script type="text/javascript">
$("document").ready(function(){
	$(".user").on("click", function(){
		var id = $(this).attr('id').slice(5);
		location.href="index.php?action=user&id=" + id;
	});
});
</script>

<div class="pageTitleBar">
	<h1>Settings</h1>
	<div style="float: right; padding: 0px 4px 4px 0; margin-left: 30px;">
		<form action="index.php"><input type="hidden" name="action" value="settings" /><input type="submit" value="System Settings" class="btn-small" /></form>	
	</div>
	
	<form id="searchFieldForm">
	<input type="text" id="searchField" name="searchField" style="float: left; margin-right: 4px;  height: 20px; width: 207px;" />
	<input type="submit" value="Search" class="btn-small" />
	</form>
			
</div>	

<?=($message ? '<div class="message' . (isset($saved) && $saved ? ' saved' : ' error') . '">' . $message . '</div>' : '')?>
	
<div class="dataTable" style="height: auto;">
	<div class="titleBar">
		<div class="options" style="float: right; line-height: 28px; padding: 0 7px 0; color: white; font-size: 10pt;">
			<form action="index.php"><input type="hidden" name="action" value="user" /><input type="hidden" name="id" value="new" /><input type="submit" value="Add User" class="btn-small" /></form>
		</div>
		<div class="caption">User List</div>
	</div>
	
	<table cellpadding="0" cellspacing="0" border="0" class="display" id="grid">
	<thead>
		<tr>
			<th class="sorting<?=($sorts['last_name'] ? '_' . strtolower($sorts['last_name']) : '')?>">Last Name</th>
			<th class="sorting<?=($sorts['first_name'] ? '_' . strtolower($sorts['first_name']) : '')?>">First Name</th>
			<th class="sorting<?=($sorts['email'] ? '_' . strtolower($sorts['email']) : '')?>">Email</th>
			<th class="sorting<?=($sorts['permission'] ? '_' . strtolower($sorts['permission']) : '')?>">Permission</th>
		</tr>
	</thead>
	<tbody>
	<? $row = 'odd'; ?>
	<? foreach($users as $user) : ?>
	
		<tr id="user_<?=$user['id']?>" class="user <?=$row?>">
			<td><?=ucfirst(strtolower($user['last_name']))?></td>
			<td><?=ucfirst(strtolower($user['first_name']))?></td>
			<td><?=$user['email']?></td>
			<td><?=$user['permission']?></td>
		</tr>
		
		<? if($row=='odd'){ $row = 'even'; } else { $row='odd'; }?>
		
	<? endforeach; ?>
	</tbody>
</table>
<div class="gridFooter">
	<div style="float: left;" id="gridPaginationText">
		Showing 1-20 of  <?= $numUsers ?> Admin Users
	</div>
	<div style="float: right;" id="gridPages">
		First			&lt; Prev			Page 1 of <?=$numPages?>			Next &gt;			Last		
	</div>
</div>