<div class="infoMain">

	<div class="titleBar">
	<div style="float: right; padding: 4px 4px 4px 0; margin-left: 30px;">
		<form action="index.php"><input type="hidden" name="action" value="users" /><input type="submit" value="User Accounts" class="btn-small" /></form>
	</div>
		<div class="caption"><?=($user['first_name'] ? $user['first_name'] . ' ' . $user['last_name'] : 'Add New User')?></div>
	</div>

	<?=($message ? '<div class="message' . (isset($saved) && $saved ? ' saved' : ' error') . '">' . $message . '</div>' : '')?>
	<form id="userForm" action="index.php" method="POST">
		<input type="hidden" name="action" value="user" />
		<input type="hidden" name="data[id]" value="<?=($user['id'] ? $user['id'] : '')?>" />

		<div class="infoBody" style="">
			<div class="infoColumn" style="padding: 0px 12px;">

				<div class="infoPane" style="margin-top: 12px;">
					<table class="infoTable" style="width: 100%;" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td colspan="2" class="infoTitle borderRight" style="width: 342px;"><h2>Account Information</h2></td>
							<td colspan="2" class="infoTitle" style="width: 344px; padding-left: 12px;"><h2>Login Information</h2></td>
						</tr>
						<tr>
							<td class="infoLabel" style="width: 96px; padding: 4px 0px 4px 12px;">First Name</td>
							<td class="infoText borderRight"><input type="text" style="width: 180px;" name="data[first_name]" value="<?=($user['first_name'] ? $user['first_name'] : '')?>" tabindex="1" /></td>

							<td class="infoLabel" style="padding: 4px 0px 4px 28px;">Email</td>
							<td class="infoText" style=""><input type="text" style="border: 1px inset silver; width: 180px;" name="data[email]" value="<?=($user['email'] ? $user['email'] : '')?>" tabindex="5" /></td>
						</tr>
						<tr>
							<td class="infoLabel" style="width: 96px; padding: 4px 0px 4px 12px;">Last Name</td>
							<td class="infoText borderRight"><input type="text" style="width: 180px;" name="data[last_name]" value="<?=($user['last_name'] ? $user['last_name'] : '')?>" tabindex="2" /></td>

							<td class="infoLabel" style="padding: 4px 0px 4px 28px;">New Password:</td>
							<td class="infoText" style=""><input type="password" style="border: 1px inset silver; width: 180px;" name="data[password]" value="" tabindex="6" /></td>
						</tr>
						<tr>
							<td class="infoLabel" style="width: 96px; padding: 4px 0px 4px 12px;">HMG Worker</td>
							<td class="infoText borderRight"><input type="text" style="width: 180px;" name="data[hmg_worker]" value="<?=($user['hmg_worker'] ? $user['hmg_worker'] : '')?>" tabindex="2" /></td>
							<td class="infoLabel" style="padding: 4px 0px 4px 28px;">Confirm Password:</td>
							<td class="infoText" style="">
								<input type="password" style="border: 1px inset silver; width: 180px;" name="password_confirm" value="" tabindex="7" />
							</td>
						</tr>
						<tr>
							<td class="infoLabel" style="width: 96px; padding: 4px 0px 4px 12px;">Permission</td>
							<td class="infoText borderRight">
								<select name="data[permission]" tabindex="3">
									<option value="Read Only"<?=($user['permission'] == 'Read Only' ? ' selected="selected"' : '')?>>Read Only</option>
									<option value="Edit"<?=($user['permission'] == 'Edit' ? '  selected="selected"' : '')?>>Edit</option>
									<option value="Admin"<?=($user['permission'] == 'Admin' ? '  selected="selected"' : '')?>>Admin</option>
								</select>
							</td>
							<td class="infoLabel" style="padding: 4px 0px 4px 28px;"></td>
							<td class="infoText" style=""></td>
						</tr>
						<tr>
							<td class="infoLabel" style="width: 96px; padding: 4px 0px 4px 12px;">Status</td>
							<td class="infoText borderRight">
								<select name="data[status]" tabindex="4">
									<option value="1"<?=($user['status'] === '1' ? '  selected="selected"' : '')?>>Active</option>
									<option value="0"<?=($user['status'] !== '1' ? '  selected="selected"' : '')?>>Inactive</option>
								</select>
							</td>

							<td class="infoLabel" style="padding: 4px 0px 4px 28px;"></td>
							<td class="infoText" style=""></td>
						</tr>
						<tr>
							<td colspan="4" style="text-align: right;">
								<input type="submit" name="save" value="Save" class="btn-small" tabindex="8" />
								<? if($user['id'] && $user['id'] != $_SESSION['user']['id']) : ?>
								<input type="submit" name="delete" value="Delete" class="btn-small" onclick="return confirm('Are you sure you want to delete this user account?');" tabindex="9" />
								<? endif; ?>
							</td>
						</tr>
						<tr>
							<td colspan="4" style="padding-top: 8px;"></td>
						</tr>

					</table>

				</div>
			</div>
		</div>
	</form>
</div>
