    <div id="sub1MainThreeCol" class="fullThreeColumnLayout">
      <?=$nav?>
      <div class="secondColumnWide"><!-- InstanceBeginEditable name="content" -->
  			<div class="inner">
				<div class="contentMain">
				<?=$main_content;?>  	
			</div>
		</div>
		<div class="thirdColumn" style="float:right; padding-left: 25px; border-left: 1px solid #aaa;">
      	<img src="images/photo.jpg" />
		</div>
	</div>
	
			