<form id="user-form" action="index.php?action=user" method="post">
<input name="id" type="hidden" />
<label for="first_name">First: </label> <input type="text" name="first_name" />
<label for="last_name">Last: </label> <input type="text" name="last_name" />
<label for="email">Email: </label> <input type="text" name="email" />
<label for="password">Password: </label> <input type="text" name="password" />
<input class="btn" type="submit" name="submit" value="<?=($id ? ' Update' : ' Add')?>" />
</form>