<div style="width: 500px; margin-right: 15px; float: left;">
<? if($err): ?>
	<div id="access-error"><?= $err ?></div>
<? endif; ?>

<h1>Welcome <?=$user['first_name']?></h1>
					
<!-- <p style="padding-bottom: 0px;">Help Me Grow Utah’s mission is to promote the optimal development of young children by</p>
<ul style="margin: 0px; padding: 0 25px 14px 25px; list-style-type: disc;">
	<li>linking families to information and community resources related to child development and parenting</li>
	<li>providing personalized care coordination</li>
	<li>creating and facilitating partnerships within the community to improve the availability and quality of services for families</li>
</ul> -->
<p><b>For help, please refer to the User Manual or contact your database manager.</b></p>
					                         
</div>